src/components/CurrencyRate.js, src/reducers/counterValues.js, src/screens/ReceiveFunds.js
this refactoring integrates the latest feature of the currencies / wallet-common libs , including the dynamic subMagnitude thing.
see the price rate under this screenshot (e.g. DOGE 1 = USD 0.00284 )
=> add CurrencyRate & use latest api

src/components/LText/AnimatedLText.js, src/components/ScrollViewAnimatedHeader.js, src/screens/Dashboard/index.js
First implementation of an animated header on scroll
you can check #58 for more informations
=> basic animated header on scroll

src/locales/en/common.json, src/screens/Settings/Help/ClearCacheRow.js, src/screens/Settings/Help/HardResetRow.js
Consistent UI with hard reset for clearing cache in settings/help
=> UI for clear cache in help/settings

android/app/build.gradle, ios/ledgerlivemobile.xcodeproj/project.pbxproj, ios/ledgerlivemobile/Info.plist, package.json, yarn.lock
This enable those icon fonts:
- Octicons
- Feather
- Entypo
- FontAwesome
- MaterialIcons
=> Add react-native-vector-icons

android/build.gradle, src/colors.js, src/components/OperationIcon.js, src/images/icons/Receive.js, src/images/icons/Send.js, src/index.js, src/screens/Dashboard/OperationRow.js, src/screens/Dashboard/index.js
=> Operations list on dashboard

src/actions/settings.js, src/locales/en/common.json, src/navigators.js, src/reducers/settings.js, src/screens/Settings/General/AnalyticsRow.js, src/screens/Settings/General/AuthSecurityToggle.js, src/screens/Settings/General/ReportErrorsRow.js, src/screens/Settings/General/index.js
Added 2 missing rows to General Settings - Analytics and Report Errors.
The UI is done and it is wired up with the state
<image src="https://user-images.githubusercontent.com/10082039/44276703-8f47ea00-a248-11e8-97c1-c24259b95953.PNG"  width="200" />
=> add UI and wire with state analytics and bugs

src/components/CurrencyUnitValue.js, src/components/OperationIcon.js, src/components/OperationRow.js, src/images/icons/Close.js, src/locales/en/common.json, src/navigators.js, src/screens/Account/index.js, src/screens/OperationDetails/Content.js, src/screens/OperationDetails/DataList.js, src/screens/OperationDetails/Footer.js, src/screens/OperationDetails/index.js, src/screens/Portfolio/index.js
Operation Detail Modal
Implemented as a full size navigation modal consistent with Send/Receive modals. Implemented as a full size also because it has to be scrollable inside and partial modals have scroll issues.
For both To/From sections implemented see more/see less spoilers. 
TODO: find consistent way for all full screen navigation modals to close on Android (swipe down feature for iOS is not an Android behavior). A closing cross or a back arrow are options.
<div><img src="https://user-images.githubusercontent.com/10082039/44517074-fe00c980-a6c6-11e8-944c-d5ebf3f0aa5d.PNG" width="200" display="inline-block"/>
=> operation details modal

src/navigators.js
missing Accounts icon tag in the tab bar
=> missing icon

src/actions/accounts.js, src/locales/en/common.json, src/navigators.js, src/reducers/accounts.js, src/screens/Account/index.js, src/screens/AccountSettings/EditAccountName.js, src/screens/AccountSettings/EditAccountUnits.js, src/screens/AccountSettings/index.js
Account Settings 
| Account Settings  | Edit Name | Edit Units | Delete
| ------------- | ------------- | ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/10082039/44719324-39ced100-aac3-11e8-8ced-188491bec29c.PNG" width="200">  | <img src="https://user-images.githubusercontent.com/10082039/44719208-db095780-aac2-11e8-942b-78dd56018009.PNG" width="200" /> | <img src="https://user-images.githubusercontent.com/10082039/44719210-dc3a8480-aac2-11e8-922c-cfc1355b0e5e.PNG" width="200" /> | <img src="https://user-images.githubusercontent.com/10082039/44719212-de044800-aac2-11e8-96a0-dcc5b7c25e63.PNG" width="200" />
=> Account settings

src/reducers/settings.js, src/screens/Settings/General/RateProviderSettings.js, src/screens/Settings/General/RateProviderSettingsRow.js, src/screens/makeGenericSelectScreen.js
General Settings screen, exchanges pairing with fiats
=> rate provider wired up with currencies in general settings

src/components/HeaderBackImage.js, src/components/HeaderTitle.js, src/images/icons/ArrowLeft.js, src/navigators.js
- Follows mockup design
- Consistent between ios/android
=> Design react-navigation screens titles

src/components/SettingsCard.js, src/screens/Settings/index.js
=> Settings UI polish

android/app/src/main/AndroidManifest.xml, src/components/SettingsCard.js, src/context/AuthPass/methods/biometry.js, src/context/AuthPass/methods/passCode.android.js, src/context/AuthPass/methods/unsupported.js
- Prevent a crash when activating screen lock on Android < 6.0 (Marshmallow)
- Fix missing line break on some devices
=> Some more Android polish

src/actions/settings.js, src/helpers/CurrencySettingsDefaults.js, src/locales/en/common.json, src/reducers/settings.js, src/screens/Settings/Currencies/CurrencySettingsSection.js, src/screens/Settings/Currencies/index.js, src/types/common.js
currency settings section. 
currently implemented with inspiration from the POC rather than the new design. to be discussed in the near future.
<div><img src="https://user-images.githubusercontent.com/10082039/44921579-377aaa00-ad43-11e8-90eb-49a9d48cf703.PNG" width="200" />
Tested on iPhoneX, iPhone SE simulator and Android (lollipop) Nexus 4
=> currency settings: exchanges and confirmation nb

src/components/Graph/index.js, src/components/GraphCard.js, src/components/provideSummary.js, src/locales/en/common.json, src/screens/Account/index.js, src/screens/Portfolio/AnimatedTopBar.js, src/screens/Portfolio/Greetings.js, src/screens/Portfolio/PortfolioGraphCard.js, src/screens/Portfolio/index.js
<p align='center'>
</p>
The graph is slightly different than in portfolio: we display value in currency + countervalue.
This has been opportunity to separate and share GraphCard component, with optional render functions.
Contains also a fix when touching the graph that was interfering with scrolling in the parent View.
Also, add the funny greetings on the portfolio ("good afternoon" etc.).
=> Graph on account, and other stuff

src/components/ElevatedView.js, src/components/GraphCard.js, src/components/SettingsCard.js, src/screens/Portfolio/AnimatedTopBar.js, src/screens/Portfolio/index.js
this is a first implementation, we might actually want to consider using less elevated shadow because these are too strong and we can't really control that
=> add Elevated, fix safe area, remove debug ui

src/screens/Portfolio/index.js
because makes no sense in infinite scroll
=> don't show scrollbar in Portfolio

src/screens/Settings/Currencies/CurrenciesList.js
also fix the list to be scrollable
=> Use FlatList in CurrenciesList

src/screens/Account/AccountHeaderRight.js, src/screens/Account/AccountHeaderTitle.js, src/screens/Account/index.js
Account Navigation Header adopted to the design and refactor of the title and headerRight rendering, removing it from ComponentDidMount
=> account native header title and header right

src/components/provideSyncRefreshControl.js, src/screens/Portfolio/AnimatedTopBar.js, src/screens/Portfolio/GraphCardContainer.js, src/screens/Portfolio/Greetings.js, src/screens/Portfolio/events.js, src/screens/Portfolio/index.js
(i'll have another PR for the rework of Account header)
=> Tweak the Portfolio animated header & fix positionning and shadow

package.json
relatable: having react-native in dep instead of peerdep caused trouble
=> @ledgerhq/react-native-ledger-core v0.2.2

.eslintrc, README.md, src/components/GenerateMockAccountsButton.js, src/components/ImportBridgeStreamData.js, src/components/LText/index.js, src/cryptocurrencies.js, src/locales/en/common.json, src/logic/account.js, src/navigators.js, src/screens/ImportAccounts/DisplayResult.js, src/screens/ImportAccounts/DisplayResultItem.js, src/screens/ImportAccounts/Scan.js, src/screens/Settings/index.js
- enabled with DEBUG_MOCK_ACCOUNT=12 env
- add BRIDGESTREAM_DATA
- document and simplify README
- many polish in import
=> Move Generate Mock Accounts into Settings

src/colors.js, src/components/StyledStatusBar.js, src/components/SyncIndicatorConnector.js, src/components/TranslatedError.js, src/errors.js, src/locales/en/common.json, src/logic/errors.js, src/screens/Account/AccountHeaderTitle.js, src/screens/Portfolio/Header.js, src/screens/Portfolio/SyncErrorHeader.js, src/screens/Portfolio/index.js
=> Portfolio sync error

android/app/build.gradle, package.json
=> Fix `yarn staging-android`

src/config/urls.js, src/screens/Settings/About/LiveReviewRow.android.js, src/screens/Settings/About/LiveReviewRow.ios.js
Fixes https://github.com/LedgerHQ/ledger-live-mobile/issues/727 although I'm not sure the link for apple is the one we have to be honest, looks weird to me.
=> Updated playstore/applestore links

src/locales/en/common.json
Fixes https://github.com/LedgerHQ/ledger-live-mobile/pull/720 (easier to create a new pr) updates wording to the latest design from zeplin.
=> Updated wording to the latest design

src/screens/Manager/Device.js, src/screens/Manager/DeviceNameRow.js
fix device name not displaying correct info after updating
=> Fixes LL-872 device name not updating

src/components/CopyLink.js, src/components/ShareLink.js, src/locales/en/common.json, src/screens/ReceiveFunds/03-Confirmation.js
=> LL-842 receive flow - share address

README.md
=> Fixed dead Play store URL

.circleci/config.yml, package.json
@gre asked for this. Fixes https://github.com/LedgerHQ/ledger-live-mobile/issues/748
=> rename: yarn ci => yarn test

src/colors.js, src/components/DeviceItemSummary.js, src/locales/en/common.json, src/screens/PairDevices/Paired.js, src/screens/PairDevices/RenderError.js, src/screens/PairDevices/index.js, yarn.lock
When the genuine check is skipped on onboarding this will show up on the UI, I also adapted the size of the checkmark/alert to match the design. It was way too big.
=> LL-984 Added style for genuine check skip, adapted size of mark

src/context/AuthPass/index.js
The app state cycle was a bit messy and the `setTimeout` wasn't triggering consistently. Since it wasn't working at all on iOS and we had a little delay when coming back until it was locked (that was deemed acceptable at the time) and since Android handles the events differently and locks a lot faster I simplified the logic a lot, removing the timeout and handling the app state changes tighter.
This should fix the lock loop that @aramab was experiencing and also make the autolock work more consistently in both platforms.
=> Autolock loop - Simplified the autolock logic, removed the timeout

src/locales/en/common.json
=> LL-1002 fix wording on app install

src/bridge/BridgeSyncContext.js, src/components/PartnerCard.js, src/families/bitcoin/BitcoinFeePerByteRow.js, src/families/ethereum/EthereumFeeRow.js, src/families/ripple/RippleFeeRow.js, src/index.js, src/libcore/scanAccountsOnDevice.js, src/screens/FirmwareUpdate/03-MCU.js, src/screens/ImportAccounts/DisplayResult.js, src/screens/Manager/AppsList.js, src/screens/OperationDetails/Footer.js, src/screens/PairDevices/Scanning.js, src/screens/PairDevices/index.js, src/screens/ReceiveFunds/03-Confirmation.js, src/screens/RepairDevice.js, src/screens/SendFunds/06-Validation.js, src/screens/Settings/About/PrivacyPolicyRow.js, src/screens/Settings/About/TermsConditionsRow.js, src/screens/Settings/Help/LedgerSupportRow.js
Added more reported errors to Sentry, removed unneeded catch blocks for links.
=> LL-983 Sentry reports, link cleanups

ios/ledgerlivemobile/Info.plist, scripts/post.sh, scripts/rnc-RNCameraManager.patch
=> 1.1.12-1 + patch script for react-native-camera

ios/ledgerlivemobile.xcodeproj/xcshareddata/xcschemes/ledgerlivemobile.xcscheme, ios/ledgerlivemobile/Info.plist
fixes a glitch with the wrong app name used because pre-actions was used and injecting the .env.staging ..
=> 1.1.12-3, need to remove these pre-actions scripts

package.json, yarn.lock
Bug fix
LL-1088
genuine check on Samsung S9 from a fresh unpaired phone.
=> Fixes LL-1088 (bluetooth timeout issue on Samsung S9)

src/components/LText/getFontStyle.android.js, src/components/LText/getFontStyle.ios.js, src/components/LText/index.js, src/locales/en/common.json, src/navigators.js, src/screens/AccountSettings/AccountAdvancedLogsRow.js, src/screens/AccountSettings/AdvancedLogs.js, src/screens/AccountSettings/index.js
Copied the displayed data from desktop basically.
=> LL-466 Advanced logs section for account settings

src/libcore/getOrCreateWallet.js
maybe the reason of NPE & some bugs regarding segwit/non-segwit (receive flow glitch)
=> Fixes important libcore code race condition!

src/components/CurrencyInput.js, src/components/LText/index.js, src/components/NoMoreOperationFooter.js, src/components/PasswordInput.js, src/components/TextInput.android.js, src/components/TextInput.ios.js, src/families/ripple/ScreenEditTag.js, src/index.js, src/navigation/navigatorConfig.js, src/navigators.js, src/screens/AccountSettings/index.js, src/screens/Settings/General/ConfirmPassword.js
It was a bit more involved than initially thought but straightforward enough, this pr fixes (or attempts to do so) the scaling issues when changing the font size scale on the system level. Ideally this should be a temporary thing and we should support some sort of font change to allow the user to adapt the font size.
Change the scaling value for both platforms and go over all screens and flows.
=> LL-1066 Fixes scaling issues in the app

src/components/SelectDevice/PairNewDeviceButton.js, src/components/SelectDevice/index.js, src/icons/ConnectNanoXIllustration.js, src/icons/Ellipsis.js, src/locales/en/common.json
- Removed the small add button and replaced it with the old full row one
- Replaced "Connect" with "Select", on Manager
- I can't get the ellipsis to be blurry @gre @aramab , lgtm
- Increased the size of the illustration to pair a new nano X
=> LL-1184 Pixel push mobile 2

src/components/CounterValue.js, src/screens/OperationDetails/Content.js, src/screens/OperationDetails/DataList.js
=> Added the countervalue field for fees on operation details

src/screens/Manager/AppIcon.js
=> fix image fading in on android in applist

src/components/SelectDevice/RemoveDeviceButton.js, src/locales/en/common.json, src/screens/Manager/Device.js, src/screens/Manager/DeviceRemoveAction.js, src/screens/Manager/RemoveRow.js, src/screens/Manager/index.js
**current inconsistencies**
The wording is in fact incorrect/unprecise, as the app can't technically UNPAIR. it's only a remove in LL data.
wording
?
manager
=> Replace "unpair" wording to "remove"

src/components/UpgradeToNanoXBanner.js, src/locales/en/common.json, src/modals/StepLegacyModal.js, src/screens/Onboarding/steps/get-started.js
=> Add modal in iOS/NanoS onboarding

src/navigators.js
Click on the current tab to scroll to the top, similar to clicking on the header.
Feature 
[LL-1204
](https://ledgerhq.atlassian.net/browse/LL-1204)
Portfolio, accounts, manager, settings
To test, scroll on any of those screens, click on the same tab and watch it scroll up.
=> LL-1204 Added refocus to bottom tabs

src/components/FilteredSearchBar.js, src/screens/AddAccounts/01-SelectCrypto.js, src/screens/Manager/AppsList.js
Improvement
LL-425
manager app list
=> adds possibility to search by ticker in manager app list

package.json, yarn.lock
=> fix bitpanda logo

src/screens/Account/index.js
it should fix the crash when delete an account but i've not effectively test it.
=> Fixes crash when deleting an account

src/components/HardResetModal.js, src/locales/en/common.json, src/screens/Settings/Help/HardResetRow.js
Remove the reset app function and instead prompt the user to uninstall and reinstall app
Improvement
LL-1327
Settings => Help => Reset Ledger Live
=> reset modal now prompts user to uninstall and reinstall app

src/locales/en/common.json
fix wording issue
wording
https://github.com/LedgerHQ/ledger-live-mobile/pull/883#issuecomment-487974577
Reset Modal
=> fix wording on reset modal

src/components/SelectDevice/BluetoothEmpty.js, src/components/SelectDevice/index.js, src/screens/Onboarding/steps/pair-new.js, src/screens/PairDevices/Paired.js, src/screens/PairDevices/index.js
Fixes onboarding pairing to automatically move to next step after coming back from adding a new device.
UX
LL-724
onboarding and selecting a device ui
=> Fixes LL-724

src/locales/en/common.json, src/screens/Manager/AppsList.js
@gre found untranslated literal
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-1374
=> LL-1374 Untranslated literal

fastlane/Fastfile
file path for ios commit was messed up
=> small fixes on fastfile

fastlane/Fastfile
=> make sure to have the latest dependencies before building

fastlane/Fastfile
=> pass env to fastlane actions

package.json, src/locales/en/common.json, yarn.lock
As far as simple prs go this has to be one of most frustrating ones so far, with flow errors, and bumps and sticks in my wheels. Regardless, this adds the description for NDAX.
Feature
https://ledgerhq.atlassian.net/browse/LL-1524
Buy crypto screen
=> LL-1524 adds NDAX description

src/components/Button.js, src/components/CurrencyIcon.js, src/components/TokenRow.js, src/locales/en/common.json, src/screens/Accounts/AccountRow.js
UI Polish
https://github.com/LedgerHQ/ledger-live-mobile/pull/931#issue-289786694
LLM Accounts screen
=> erc 20 account screen OK

src/components/CounterValue.js, src/components/TokenRow.js, src/locales/en/common.json, src/screens/Account/TokenAccountsList.js, src/screens/Accounts/AccountRow.js
UI Polish
https://github.com/LedgerHQ/ledger-live-mobile/pull/931
LLM account screen
=> added erc20 list on account screen

src/components/AccountCard.js, src/components/CurrencyIcon.js, src/helpers/formatAccountSearchResults.js, src/screens/Portfolio/Header.js, src/screens/ReceiveFunds/01-SelectAccount.js, src/screens/SendFunds/01-SelectAccount.js
Feature
https://github.com/LedgerHQ/ledger-live-mobile/pull/931
Receive / Send account select screen
=> filters for erc20 tokens

.eslintrc, package.json, yarn.lock
Added a react-hooks eslint rule plugin
Code Quality Improvement
LL-1639
Eslint config, whole app coding style
=> added react hooks eslint rule

.flowconfig, src/families/ethereum/EthereumFeeRow.js, src/families/ethereum/TokenNetworkFeeInfo.js, src/locales/en/common.json, src/screens/Distribution/DistributionCard.js, src/screens/SendFunds/SummaryTotalSection.js
Touching "Network fees" now open an info drawer.
Feature
LL-1436
Ethereum kind receive screen
=> Ll 1436/token account fee drawer

src/screens/Settings/Experimental/index.js
bug fix
LL-1698
Experimental feature settings screen
=> fixed padding in experimental settings

src/screens/AddAccounts/03-Accounts.js, src/screens/SendFunds/02-SelectRecipient.js
Sending tokens using QR code now works properly
Bug Fix
LL-1694
Send => Select recipient => QR Scanner
=> Ll 1694/qr code send tokens

src/screens/SendFunds/03-Amount.js
The sendmax button was not working for tokens because the bridge was not being retrieved correctly.
BugFix
https://ledgerhq.atlassian.net/projects/LL/issues/LL-1693
Send flow, amount step, sending from token account
=> LL-1693 Fixes send max broken button for erc20

src/screens/SendFunds/04-Summary.js, src/screens/SendFunds/ValidateOnDevice.js
Addresses the issues with displayed amount/fees when using sendmax.
BugFix
https://ledgerhq.atlassian.net/browse/LL-1692
Send flow, using send max (not tokens until https://github.com/LedgerHQ/ledger-live-mobile/pull/970 is merged) check the summary and verification values for fees and amount
=> LL-1692 Fixes to sendmax displayed amounts

src/locales/en/common.json
fix some wording issues with tokens
ui polish
N / A
token wording
=> Fix wording

src/screens/Accounts/AccountRow.js
fixing a regression with show tokens not appearing anymore in account list
bug fix
LL-1718
accounts screen -> account row
=> fixed regression

src/screens/OperationDetails/Content.js
Bug fix
LL-1691
Operation Details data screen / Extra rows (XRP tag row for instance)
=> LL-1691 fixed extra row colours being not set

src/screens/OperationDetails/Content.js
Removing the fee column from IN operations (receives)
UI Polish
LL-1709
Operation Data Screen -> Fee row
=> LL-1709 removing fees on IN operations

src/components/SelectableAccountsList.js, src/locales/en/common.json
Feature
https://ledgerhq.atlassian.net/browse/LL-1591
Add account
=> LL-1591 Show token count on Add account

src/components/TokenRow.js, src/screens/Accounts/AccountRow.js
UI Polish
N/A
Accounts Screen => nested Token rows
=> fixed token row style to match zeplin

src/locales/en/common.json
UI Polish
LL-1772
Add account flow => navigation bar
=> added step to the add account flow navigation bar

src/locales/en/common.json, src/navigators.js, src/screens/Account/TokenAccountsList.js, src/screens/Accounts/AccountRow.js
UI Polish
https://ledgerhq.atlassian.net/browse/LL-1817
=> LL-1817 Allow plural/singural wording for tokens

android/app/src/main/java/com/ledger/live/MainActivity.java, src/actions/accounts.js, src/components/Rounded.js, src/components/RoundedCurrencyIcon.js, src/components/SelectDevice/index.js, src/locales/en/common.json, src/navigators.js, src/reducers/accounts.js, src/screens/Accounts/index.js, src/screens/MigrateAccounts/01-Overview.js, src/screens/MigrateAccounts/02-ConnectDevice.js, src/screens/MigrateAccounts/03-Progress.js, src/screens/MigrateAccounts/Banner.js, src/screens/Portfolio/index.js
Feature
https://ledgerhq.atlassian.net/browse/LL-1615
=> LL-1615 Account migration flow

src/components/ExternalLink.js, src/config/urls.js, src/locales/en/common.json, src/screens/OperationDetails/Content.js, src/screens/OperationDetails/DataList.js
see title ^
Improvement
LL-1795
Operation Details
=> add support link for operation detail when multiple destination addresses

src/components/CurrencyIcon.js, src/components/CurrencyRow.js, src/components/ExternalLink.js, src/locales/en/common.json, src/navigators.js, src/screens/AddAccounts/01-SelectCrypto.js, src/screens/AddAccounts/02-TokenCurrencyDisclaimer.js
Possibility to see the ERC20 Tokens in the select component when adding a new account
Also added the page when selecting ERC20 when adding accont
Feat
LL-1846
Add account modal
=> add tokens to list in add account modal

src/screens/SendFunds/ValidateOnDevice.js
UI Polish
Discussion with gre
send funds screen -> validate on device step -> fees data row
=> hiding data row when fees = 0

src/components/HardResetModal.js, src/locales/en/common.json
Rollback of the libcore call to reset the data in the app, it apparently is causing some bugs on iOS
Rollback
https://ledgerhq.atlassian.net/browse/LL-1895
Reset feature
=> LL-1895 Rollback reset functionality

src/components/HeaderErrorTitle.js
UI Polish
Sync error on header portfolio/account
=> Limit the lines of error on header

src/components/QRCodePreview.js
reverted from rich address format to just address (assetname:address => address)
bug fix ?
LL-1873
Qr Code
=> switched from currency:address to just address

src/screens/Accounts/AccountRow.js
reworked account rows to prevent account name being clipped.
Bug Fix
LL-1851
Accounts -> Account Row
=> fixed account name clipped

src/actions/portfolio.js, src/components/AccountDistribution/Row.js, src/components/AccountDistribution/index.js, src/components/AssetGraphCard.js, src/components/Pills.js, src/locales/en/common.json, src/navigators.js, src/screens/Accounts/AccountRow.js, src/screens/Asset/index.js, src/screens/Distribution/index.js
New screen, only accessible in this commit through the asset distribution screen. This will be changed in future commits to follow the new portfolio flow.
Half Feature
https://ledgerhq.atlassian.net/browse/LL-1826
New screen, accessible from the asset distribution rows.
=> LL-1826 Adds Asset screen

package.json, src/live-common-setup.js, yarn.lock
Fixes bug related to iOS 13 support.
Bug fix
LL-1932
LL-1934
test everything related to libcore. send flow mainly.
=> Fixes iOS 13 related bug

src/screens/ImportAccounts/DisplayResult.js, src/screens/OperationDetails/Modal.js
title says it all
UI Polish
LL-1886
Import Accounts (with QR Code)
=> add safearea to import account

src/screens/AddAccounts/01-SelectCrypto.js
add account's asset list now filter token + asset by marketcap. 
Feature
LL-1883
AddAccounts -> SelectCurrency -> CurrencyList
=> llm now filter by marketcap

src/components/CurrencyIcon.js, src/screens/Accounts/AccountRow.js, src/screens/MigrateAccounts/01-Overview.js, src/screens/MigrateAccounts/03-Progress.js
=> fix wording on accounts page to display token or subaccount wording

src/experimental.js, yarn.lock
like https://github.com/LedgerHQ/ledger-live-desktop/pull/2450
=> xtz experimental

fastlane/Fastfile
=> set xcode version in fastlane

src/actions/general.js, src/bridge/cache.js
clear cache to clear preloaded currency data
polish
LL-2052
clear cache / xtz
=> Fixes LL-2052

android/app/src/main/res/values/styles.xml
OCD trigger fix
Contender for most important PR of the year.
Your turn @IAmMorrow
=> [Android] Fix accent color for cursor and switches

src/bridge/cache.js, src/families/bitcoin/screens.js, src/families/ethereum/screens.js, src/families/ripple/screens.js
- Fix deprecated import for AsyncStorage
- Fix broken edit fees link in send flow
Bug Fixes
RN 0.61 migration
=> Various RN 0.61 fixes

src/components/TextInput.android.js
Unlike on iOS, Android multiline text inputs don't dynamically update their height to follow content size change.
This should fix that.
Also, for whatever reason, the Recipient address field on Android wasn't multiline and was scrolling horizontally on our RN 0.59 app, and ended up in a broken multiline when moving to 0.61, so this also fix that.
Bugfix turned feature
RN 0.61 migration
Multiline text inputs on Android
=> [Android] Dynamic height for multiline text inputs

package.json, src/bridge/BridgeSyncContext.js, src/bridge/cache.js, src/families/tezos/DelegationFlow/SelectValidator.js, src/families/tezos/DelegationFlow/Summary.js, yarn.lock
=> Polish delegation

src/locales/en/common.json
Updated wording for the experimental features disclaimer
Wording
https://ledgerhq.atlassian.net/browse/LL-2057
Experimental features disclaimer
=> LL-2057 Updated wording for experimental features disclaimer

package.json, scripts/post.sh
Also added `yarn pod` to update Cocoapods after changing native deps
=> Add a friendly meaningful error for Podfile.lock 📎

src/families/tezos/DelegationFlow/Summary.js, src/locales/en/common.json
Wording
Tezos integration
Delegate flow
=> Add some legalese on delegate screen

scripts/sync-families-dispatch.sh, src/families/tezos/operationDetails.js, src/locales/en/common.json, src/screens/OperationDetails/Footer.js, src/screens/OperationDetails/index.js
same as https://github.com/LedgerHQ/ledger-live-desktop/pull/2534
=> Custom link on operation details for xtz

src/screens/OperationDetails/Content.js
=> hide TO in operation details when there are no recipients

android/app/src/main/java/com/ledger/live/MainActivity.java
according to our sentry, these can be null.
=> Fixes a crash that some users experience

src/locales/en/common.json
Missing description 
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-2093
Partners screen
=> LL-2093 Add missing description

src/components/InfoModal.js, src/families/tezos/DelegationFlow/SelectValidator.js, src/locales/en/common.json
UI Polish
LL-2091
Delegation Flows
=> LL-2091 add a link to mytezosbaker for est. yields

.github/workflows/CI.yml
Port CircleCI flows to github actions
=> setup github actions to replace circleci

src/components/DeviceItem.js, src/components/DeviceItemSummary.js, src/locales/en/common.json, src/navigators.js, src/screens/Manager/AppsScreen.js, src/screens/Manager/Device/DeviceAppStorage.js, src/screens/Manager/Device/DeviceName.js, src/screens/Manager/index.js
QA
fixed
* UI can’t handle long device name
Bug Fix
LL-2075
Manager V2
=> LL-2075 (ManagerV2): qa polish

package.json, yarn.lock
bump live common version to 12.0.x version
=> bump live-common 12.0.x

src/locales/en/common.json
Some wording polish mainly on manager v2
Wording
LL-2203
=> LL-2203 (Wording): fix

package.json, src/screens/Manager/AppsList/AppInstallProgress.js, src/screens/Manager/AppsList/AppRow.js, src/screens/Manager/AppsList/AppStateButton.js, src/screens/Manager/AppsList/index.js, src/screens/Manager/AppsScreen.js, src/screens/Manager/Manager.js, src/screens/Manager/Modals/SearchModal.js, yarn.lock
Manager:
updated progress bar in order to use observable hook.
Polish
LL-2237
Manager:
Install one or more apps to see better rendering perfs on the progress bar and whole manager view
=> LL-2237 (Manager): install progress  now uses observable hook

src/components/BottomModal.js, src/components/RequireTerms.js, src/index.js, src/screens/Settings/About/TermsConditionsRow.js
Improvement
LL-2311
Settings > About ? Terms and Conditions
=> see terms and coditions from settings>about

.github/workflows/CI.yml
=> prevent user ledgerlive from triggering CI

src/screens/SendFunds/03-Amount.js
Send Flow => Estimate is now correct instead of using account.balance, we use estimateMaxSpendable
Tested on iOS, seems to work
=> use estimateMaxSpendable on mobile

src/families/tron/TransactionConfirmFields.js
similar as in https://github.com/LedgerHQ/ledger-live-desktop/pull/2802
=> Tron device flow

src/screens/UnfreezeFunds/01-Amount.js
(TRX): freeze flow disable resource condition take expiredAt in account
Bug Fix
LL-2338
Trx accounts that can unfreeze, has frozen assets but can't unfreeze a given resource cause of expiredAt date
=> LL-2338 Freeze flow issue

src/families/tron/VotingFlow/02-VoteModal.js
Fixes a glitch in iOS keyboard for votes.
**To be tested:**
- iOS have the fix
- Android still is fine.
=> Fixes LL-2377

src/components/OperationRow.js, src/families/tron/operationDetails.js
Add trx amount details to the operation list
UI Polish
LL-2278
operation details list for trx freeze unfreeze and vote types
=> Trx operation details list amount

src/locales/en/common.json
Wording update for frozen assets tooltip
Wording
Click on frozen assets button to see the info
=> (TRX): frozen assets wording updated

src/locales/en/common.json, src/locales/es/common.json, src/locales/fr/common.json, src/locales/ja/common.json, src/locales/ko/common.json, src/locales/ru/common.json, src/locales/zh/common.json
Fixed wording on remaining votes section of TRX
Wording
=> (TRX): fix wording

src/screens/Account/AccountHeaderRight.js, src/screens/Account/TokenContractAddress.js
Updated contract address modal to not show if no url available.
UI Polish
Trx trc10 tokens
Tokens contract info modal
=> (TRX): contract address modal don't show if no url available

src/components/Button.js, src/families/tron/Votes/Header.js, src/screens/Account/AccountActions.js, src/screens/FreezeFunds/01-Info.js, src/screens/FreezeFunds/02-Amount.js, src/screens/UnfreezeFunds/01-Amount.js
Issues on small screen on the accounts page of trx accounts
**On small screens**
**On bigger ones**
UI Polish
Open trx account page on a small device ie: iphone 5S
=> (TRX): issues on small screen on accounts page

src/locales/en/common.json
Sync wording to match https://github.com/LedgerHQ/ledger-live-desktop/blob/c5c78e3e46693f68ea31b57c83c103ccc4bc4d07/static/i18n/ko/app.json#L1769-L1771
=> Sync wording for NotEnoughSpendableBalance

src/screens/SendFunds/07-ValidationSuccess.js
operation details afetr a sent of token now redirects to the suboperation if available
UI Polish
Send a transaction from a token to a token and click on the preview of the operation details to see the correct translation wording
=> (trx): token operation details after send success issue

src/families/tron/VotingFlow/02-VoteModal.js
Issue was occurring on cast votes modal when keyboard was open
should be fixed now:
UI Polish
Trx account that can vote
try and edit a vote.
=> (TRX): fixed issue on cast votes modal and keyboard open

src/families/tron/accountActions.js, src/screens/Account/AccountActions.js
issue occuring on trc tokens send receive butons having scroll
UI Polish
Go to a trc token page you should see same send receive buttons as normal currencies.
=> (TRX): fix send receive button on trc tokens having scroll

src/screens/Settings/Accounts/BlacklistTokenModal.js
Please test on both ios and android, if testing on ios simulator use the `yarn hack-for-ios-simulator` command before running it so it works.
=> fix freeze on blacklist token for ios'

src/screens/UnfreezeFunds/01-Amount.js
Operation details list info was missing on develop
https://github.com/LedgerHQ/ledger-live-mobile/pull/1220
=> LL-2278 operation details list not merged

src/screens/Manager/AppsList/AppInstallButton.js, src/screens/Manager/Manager.js, src/screens/Manager/Modals/StorageWarningModal.js
Issue on manager install buttons alignments and storage warning modal
UI Polish
Manager screen
=> (Manager): fix ui regression buttons issue and warnig modal

src/locales/en/common.json, src/locales/es/common.json, src/locales/fr/common.json, src/locales/ja/common.json, src/locales/ko/common.json, src/locales/ru/common.json, src/locales/zh/common.json, src/screens/AddAccounts/02-TokenCurrencyDisclaimer.js
wording issue on add tokens page title and case on bottom buttons
Wording
Add token assets screen
=> (Wording): fix add token assets wording

src/modals/PasslockDisclaimerModal.js, src/modals/Pin.js, src/modals/RecoveryPhrase.js, src/modals/StepLegacyModal.js
issue on got it button on onboarding
UI Polish
Follow onboarding as a new device to view this info modal
=> (Onboarding): fixed Got it button ui vertical align

src/families/tron/VotingFlow/01-SelectValidator/index.js, src/families/tron/VotingFlow/02-CastVote.js
When you navigate to step 2, press "Add more votes", then click android back button, you'll end up on Step 1 again. The android back button should navigate to step 2.
=> Fix nav issue after pressing "add more votes" on My votes step

package.json
Should have been part of #1206 but was lost when merging `develop` in that PR.
Bug Fix
#1206
Running `yarn ios:staging` should work.
=> [iOS] Fix staging on simulator

package.json, src/locales/en/common.json, yarn.lock
live-common
- https://github.com/LedgerHQ/ledger-live-common/pull/623
- LL-2283
check the impact with the contextual info mentioned above.
=> live-common 12.18.0

src/components/AccountDistribution/index.js, src/locales/en/common.json
=> fix account distribution title

src/screens/Account/SubAccountsList.js, src/screens/Accounts/index.js, src/screens/ImportAccounts/DisplayResult.js
- Fix crash on navigation after importing accounts via QR code.
- Fix warning on long press token account on accounts screen (debug build)
- Fix warning on long press token account on account screen (debug build)
=> Hotfix import accounts

src/components/DeviceJob/StepRenders.js, src/components/DeviceJob/StepRunnerModal.js, src/components/DeviceJob/steps.js, src/components/DeviceJob/types.js, src/locales/en/common.json
=> LL-2451 Add go to manager button on bottom modal

src/components/ValidateOnDeviceDataRow.js, src/const/navigation.js, src/families/cosmos/TransactionConfirmFields.js, src/locales/en/common.json
=> Cosmos Transaction Verification screen

src/families/cosmos/operationDetails.js, src/screens/OperationDetails/Content.js, src/screens/OperationDetails/Section.js
=> Add fee info url on operation details

src/screens/ClaimRewards/02-Validation.js
Tron claim rewards flow issue on the final validation step
Bug Fix
Use a tron account with rewards available and try claim them
=> (tron): fix claim rewards validation issue

src/screens/Settings/General/BiometricsRow.js
Navigate to General settings and disable Face ID/Fingerprint. It should require a biometric authentication to disabled it.
=> Require biometric auth to disable the feature

src/screens/Account/AccountActions.js
I'm not the biggest fan but it works
=> account actions now horizontally scroll when the asset is buyable

src/actions/settings.js, src/components/HeaderRightClose.js, src/components/RootNavigator/ManagerNavigator.js, src/locales/en/common.json, src/reducers/settings.js, src/screens/Manager/Device/index.js, src/screens/Manager/Manager.js, src/screens/Manager/Modals/ActionModal.js, src/screens/Manager/Modals/FirmwareUpdateModal.js
When user gets into Manager, we check if a new firmware is available, and guide him to LLD
https://ledgerhq.atlassian.net/browse/LL-2702
https://ledgerhq.atlassian.net/browse/LL-2704
Manager and Bottom Menu
=> inform user about a firmware update

src/components/DeviceJob/StepRenders.js
would you like some padding
UI Polish (regression ?)
My eyes
=> we lost some padding

src/config/urls.js
Change learn more link in the last step of the receive flow.
Link change
LL-2792
Go to the last step of a receive flow and check the link redirects to the correct url (check main ticket for it)
=> LL-2792 (ReceiveFlow): change learn more link

src/screens/Exchange/SelectAccount.js
(BuyCrypto): Select account has an add account button at the end of the list as well
UI Polish
LL-2697
Follow the buy crypto flow up until the select account step.
=> LL-2697 BuyCrypto add account button

src/icons/Academy.js, src/screens/Settings/HelpButton.js
updated to the new ledger academy icon
=> fixing academy icon

src/families/tezos/DelegationFlow/SelectValidator.js
Updated tezos provider name and url in the information.
Wording
LL-2777
When choosing a new validator the provider information should be updated accordingly.
=> LL-2777 (Wording): tezos update provider name and url

src/components/RootNavigator/BaseNavigator.js
Operation type added to header title
UI Polish
LL-2823
operation details screen header title.
=> LL-2823 (OperationDetails): operation type added to header title

src/locales/en/common.json
Updated cosmos wordings according to the LLD version.
Wording
LL-2875
Earn rewards info stepper
Validate on device for redelegation operations
=> LL-2875 (Cosmos): wording updates

src/components/ValidateOnDevice.js
=> LL-2829 Tx amount should be displayed

ios/Podfile.lock, src/const/navigation.js, src/experimental.js, src/screens/Settings/Experimental/FeatureInteger.js, src/screens/Settings/Experimental/FeatureRow.js, src/screens/Settings/Experimental/index.js, src/screens/Settings/General/BiometricsRow.js
Feat
LL-2900
Experimental Settings
=> add manager provider to experimental settings

src/components/RootNavigator/BaseNavigator.js, src/components/RootNavigator/ClaimRewardsNavigator.js, src/components/RootNavigator/FreezeNavigator.js, src/components/RootNavigator/SendFundsNavigator.js, src/components/RootNavigator/UnfreezeNavigator.js, src/families/cosmos/ClaimRewardsFlow/index.js, src/families/cosmos/DelegationFlow/index.js, src/families/cosmos/RedelegationFlow/index.js, src/families/cosmos/UndelegationFlow/index.js, src/families/tezos/DelegationFlow/index.js, src/families/tron/VoteFlow/index.js
Fix
L-2893
Freeze / Unfreeze / Delegate / Vote Flows success screens
=> remove back navigation arrow on success screen - fixes LL-2893

src/components/ValidateOnDevice.js
Fix
LL-3055
Send Flow Validation Screen
=> use erc20 unit when available in validation screen

src/components/DeviceJob/steps.js, src/screens/ReceiveFunds/03-Confirmation.js
(DeviceAction): update receive address flow to match bch cashaddr issues fix from live-common
Bug Fix
LL-3056
Receive flows and verification address steps.
(to test on several currencies and specially on BCH)
=> LL-3056 (DeviceAction): update receive address flow

src/components/CurrencyInput.js, src/families/tron/VoteFlow/02-VoteModal.js, src/screens/Settings/CryptoAssets/Rates/Price.js
Remove deprecated font Rubik from styles
Bug Fix
Send flow currency inputs should now be inter like everything else
=> (Fonts): replace Rubik font

package.json, yarn.lock
bump libcore bindings should fix cosmos amplifier issue
=> bump libcore bindings 4.15.10

src/components/DeviceJob/steps.js
(BuyFlow): fix issue where meta not present for wordings with a fail safe on the data
Bug Fix
Slack
Test the buy flow from A-Z and maybe some send and receive flow
=> Fix buy flow crash issue

package.json, yarn.lock
bump libcore bindings 4.15.11
should fix tezos tx issue
=> bump libcore bindings 4.15.12

src/components/LText/getFontStyle.ios.js
=> fix(ios): font weights

src/families/algorand/Rewards/ClaimRewardsFlow/01-Started.js, src/families/algorand/Rewards/index.js
LL-3105 LL-3106 fix rewards and claim rewards flow on small devices
fix scroll area on claim rewards for small screens + fix rewards amount on account page rewards section
UI Polish
LL-3105 LL-3106
Algorand accounts with rewards.
=> LL-3105 LL-3106 fix rewards and claim rewards flow on small devices

package.json, yarn.lock
=> bump libcore v4.15.13

src/families/algorand/SendRowsFee.js
Algo fees for ASA updated with correct unit in summary view.
Bug Fix
Slack
Try making an ASA transaction, Fees should now be expressed in Algo.
=> (Algo): send fees summary unit updated with correct value for ASA

src/families/cosmos/AccountBalanceSummaryFooter.js, src/families/cosmos/DelegationFlow/01-Started.js
Remove earn rewards title from cosmos flow since its unused.
UI Polish
LL-3069
Cosmos earn rewards modal during the delegation flow
=> LL-3069 Cosmos earn rewards title issue

src/locales/en/common.json, src/screens/Manager/Modals/SearchModal.js
(Manager): change add tokens wording
Wording
LL-3128
Manager search with tokens
=> LL-3128 (Manager): change add tokens wording

src/screens/ConnectDevice.js, src/screens/SendFunds/04-Summary.js
=> LL-3459 Fix ERC20 unit on tx verification screen

src/components/DeviceAction/rendering.js
=> Spin loading indicator clockwise

src/screens/Swap/Connect.js, src/screens/Swap/Form/Error.js, src/screens/Swap/Form/Summary/index.js, src/screens/Swap/Form/index.js, src/screens/Swap/History/index.js, src/screens/Swap/Landing.js, src/screens/Swap/MissingOrOutdatedSwapApp.js, src/screens/Swap/NotAvailable.js
Adds analytics events tracking for the swap flow just like we did for LLD.
Feature
Test that the swap flow doesn't break due to this, it shouldn't, but hey, worth checking.
=> Add analytics events for LLM swap

package.json, src/components/banners/SwapBanner.js, src/locales/en/common.json, src/screens/Portfolio/index.js, src/screens/Swap/Confirmation.js, src/screens/Swap/Form/PendingOperation.js, src/screens/Swap/Form/SelectAccount/01-SelectCrypto.js, src/screens/Swap/Form/SelectAccount/02-SelectAccount.js, src/screens/Swap/Form/SelectAccount/BadSelectionModal.js, src/screens/Swap/Form/Summary/SummaryBody.js, src/screens/Swap/FormOrHistory.js, src/screens/Swap/History/index.js, src/screens/Swap/Landing.js, src/screens/Swap/OperationDetails.js, src/screens/Swap/SwapStatusIndicator.js, yarn.lock
Since most of the tasks are small and don't require a new pr to test them, I'm grouping them here to make it easier for @Arnaud97234 to test. I'll link to the individual tasks that are addressed and you can check the boxes for those that are ok.
- Check that no wording is broken while doing the other checks
- Match against the ticket to be extra sure I didn't miss something.
- Go to swap flow
- Select currency
- Make sure the Add Account CTA is not present, not on the FROM flow, not on the TO flow.
- Go to swap flow (before accepting the KYC checkbox)
- Make sure the disclaimer footer text does not overflow to the right, in particular on an iPhone 7 according to the issue.
- Go to swap flow
- Make sure the tab navigation styles match the Buy feature (Capital casing, and semibold)
- Launch …
=> Swap - Grouped fixes for the release

src/screens/AddAccounts/02-SelectDevice.js, src/screens/AddAccounts/02-TokenCurrencyDisclaimer.js, src/screens/AddAccounts/03-Accounts.js, src/screens/AddAccounts/04-Success.js
Feature
https://ledgerhq.atlassian.net/browse/LL-3551
Don't know how to validate these
=> LL-3551 Analytics track currency name on add account flow

src/components/CurrencyDownStatusAlert.js, src/components/ExternalLink.js, src/components/WarningBanner.js, src/config/urls.js, src/locales/en/common.json, src/screens/Portfolio/GraphCardContainer.js, src/screens/Portfolio/index.js
Like https://github.com/LedgerHQ/ledger-live-desktop/pull/3238 but only on portfolio.
It should look like figma design with no external link icon as per design and since i could not get it to align properly with the rest of the text.
=> Add BCH hardfork warning banner

ios/ledgerlivemobile.xcodeproj/project.pbxproj
=> change build settings to fit foor xcode 12

src/reducers/accounts.js, src/screens/ReceiveFunds/02-ConnectDevice.js, src/screens/ReceiveFunds/03-Confirmation.js
Fixes regression created by https://github.com/LedgerHQ/ledger-live-mobile/commit/cdd07471d87cdd0c46b3a508059203d5457709cc
=> Fixes access of receive flow from an account

src/components/DelegationDrawer.js, src/families/ethereum/operationDetails.js, src/icons/OperationStatusIcon/Enable.js, src/icons/OperationStatusIcon/Supply.js, src/icons/OperationStatusIcon/Withdraw.js, src/icons/OperationStatusIcon/index.js, src/icons/Withdraw.js, src/locales/en/common.json, src/logic/screenTransactionHooks.js, src/screens/Account/hooks/useLendingActions.js, src/screens/Lending/Account/AccountBodyHeader.js, src/screens/Lending/ClosedLoans/ClosedLoansRow.js, src/screens/Lending/Dashboard/ActiveAccountRow.js, src/screens/Lending/Dashboard/ActiveAccounts.js, src/screens/Lending/Dashboard/index.js, src/screens/Lending/EnableFlow/04-ValidationError.js, src/screens/Lending/EnableFlow/04-ValidationSuccess.js, src/screens/Lending/SupplyFlow/03-ValidationError.js, src/screens/Lending/SupplyFlow/03-ValidationSuccess.js, src/screens/Lending/WithdrawFlow/03-ValidationError.js, src/screens/Lending/WithdrawFlow/03-ValidationSuccess.js, src/screens/Lending/modals/BaseModal.js
Fixes compound
- fix account name too long on active accounts and closed loans rows
- fix can supply before approving an account from the account page actions
- fix step error crashes during flows
Bug fix
LL-3335
=> (Lending): fix ui

src/locales/en/common.json
change currency display 
ui
https://ledgerhq.atlassian.net/browse/LL-2766
=> LL-2766 – wording change on countervalue

package.json, src/components/ValidateOnDevice.js, src/components/banners/OngoingScams.js, src/config/urls.js, src/locales/en/common.json, src/screens/Lending/EnableFlow/02-Amount/Advanced.js, src/screens/Lending/EnableFlow/02-Amount/index.js, src/screens/Lending/EnableFlow/04-ValidationSuccess.js, src/screens/Lending/SupplyFlow/03-ValidationSuccess.js, src/screens/Lending/WithdrawFlow/03-ValidationSuccess.js, src/screens/Portfolio/index.js, yarn.lock
This PR is a _compound_ PR containing 3 other PRs in order to facilitate testing their respective work.
- https://github.com/LedgerHQ/ledger-live-mobile/pull/1433
- https://github.com/LedgerHQ/ledger-live-mobile/pull/1443
- https://github.com/LedgerHQ/ledger-live-mobile/pull/1444
=> 2.16.0 remaining work to QA

src/components/banners/OngoingScams.js, src/config/urls.js, src/locales/en/common.json, src/screens/Portfolio/index.js
Feature
https://ledgerhq.atlassian.net/browse/LL-3775
- Test that the notice shows, test that it can be dismissed.
=> LL-3775 Add a warning banner for ongoing scam campaigns

package.json, src/locales/en/common.json, yarn.lock
- should fixes recent TRON issues
- check that some compound / erc20 txs still works (some refinement in gasLImit calculation)
=> live-common 15.7.6

.github/actions/change-product-name/action.yml, .github/actions/change-product-name/index.js, .github/workflows/bundle-app.yml, package.json, scripts/post.sh, yarn.lock
add android build on CI workflow
Improvement
https://ledgerhq.atlassian.net/browse/LL-3800
check if there is an android apk available in this commit !
=> Ll 3800 Build apk on every commit

src/components/RootNavigator/LendingInfoNavigator.js, src/screens/Lending/modals/InfoModals/TermsStep.js
(Lending): prevent native back gesture during TaC screen
Bug fix
LL-3870
Compound start flow TaC screen.
=> LL-3870 (Lending): prevent native back gesture during TaC screen

src/config/urls.js
update buyNanoX url
fix
https://ledgerhq.atlassian.net/browse/LL-3770
Check to click on a buy NanoX link and check that there are analytics parameters in the querystring
=> LL-3770 update buyNanoX url

src/families/cosmos/DelegationFlow/01-Started.js
(Cosmos): update support urls
Polish
LL-3037
Cosmos support url in first delegation step
=> LL-3037 (Cosmos): update support urls

src/components/Carousel/slides/BackupPack.js, src/components/Carousel/slides/BuyCrypto.js, src/components/Carousel/slides/LedgerAcademy.js, src/components/Carousel/slides/Lending.js, src/components/Carousel/slides/Sell.js, src/components/Carousel/slides/StakeAlgo.js, src/components/Carousel/slides/StakeCosmos.js, src/components/Carousel/slides/Swap.js, src/components/Carousel/slides/Vote.js
Add click events on carousel
feature
https://ledgerhq.atlassian.net/browse/LL-3761
Click on the carousel
=> add carousel click events

src/components/Carousel/slides/BlackFriday.js
https://ledgerhq.atlassian.net/browse/LL-3904
=> fix black banner

src/components/DisplayAddress.js
https://ledgerhq.atlassian.net/browse/LL-3839
=> LL-3839 disable ellipsis on DisplayAddress

package.json, src/components/RootNavigator/LendingNavigator.js, src/screens/Lending/ClosedLoans/index.js, src/screens/Lending/History/index.js, src/screens/Lending/useCompoundSummaries.js, yarn.lock
Bug Fix
Lending screen doesn't display anything under the top tab
Lending screens
=> Fix Lending screen

src/components/AccountCard.js
https://ledgerhq.atlassian.net/browse/LL-3878
=> LL-3878 fix balance in first step of send flow

src/config/urls.js, src/locales/en/common.json
Million wording changes, one by one, manually baked from an ancient text from July.
Wording
https://ledgerhq.atlassian.net/browse/LL-3860
=> LL-3860 Wording changes, lots of wording changes

src/components/CheckBox.js, src/locales/en/common.json, src/screens/Lending/modals/InfoModals/TermsStep.js
Fix onClick from full text to link only in Terms and Conditions Modal
Fix
LL-3869
=> TAC modal onClick only on link

src/screens/Lending/shared/LendingWarnings.js
(Lending): removal of eth high fees modal
Feature
LL-3940
Lending flow should not show eth high fees modal anymore
=> LL-3940 (Lending): removal of eth high fees modal

src/components/RootNavigator/ExchangeNavigator.js, src/components/RootNavigator/SettingsNavigator.js, src/const/navigation.js, src/locales/en/common.json, src/screens/Settings/Accounts/index.js, src/screens/Settings/index.js
- Move crypto Assets Settings inside Accounts settings
- Change wordings
UI Polish
LL-3522
Settings -> Accounts -> Crypto Assets
=> LL-3522 Move crypto Assets Settings inside Accounts settings

src/components/RootNavigator/MainNavigator.js, src/config/urls.js, src/screens/Onboarding/steps/welcome.js, src/screens/Settings/PoweredByLedger.js, src/screens/Settings/index.js
This reverts the logic that made the Powered by ledger component trigger the debug menu.
With this rollback we should prevent the crash that @Arnaud97234 experienced and @gre figured out, on the Auth screen.
=> Revert powered by ledger debug access

src/locales/en/common.json, src/screens/SendFunds/04-Summary.js, src/screens/SendFunds/TooMuchUTXOBottomModal.js
https://ledgerhq.atlassian.net/browse/LL-2847
i've seen the feedback on lld, i will update
=> add a utxo warning when utxo > 50

src/locales/en/common.json, src/screens/Lending/EnableFlow/01-SelectAccount.js
https://ledgerhq.atlassian.net/browse/LL-3960
=> Ll 3960 - fix info box on lending select account step

src/screens/Manager/Modals/SearchModal.js
https://ledgerhq.atlassian.net/browse/LL-4164
- Go to Manager
- Search ERC20 / TRC20 / TRC10 token
=> LL-4164 - Fix title: Manager search results for tokens

src/config/urls.js, src/locales/en/common.json, src/screens/Onboarding/steps/terms.js
(Onboarding): term checkboxs wording updated
Wording
LL-4248
Terms page checkbox wording
=> LL-4248 (Onboarding): term checkboxs wording updated

src/config/urls.js, src/locales/en/common.json, src/screens/Onboarding/steps/terms.js
=> 2.19 patch

src/components/OnboardingStepperView/OnboardingStepView.js
(Onboarding): fix some vertical scrolling issue
UI Polish
LL-4243
Onboarding step views should now have cta fixed at the bottom of the screen
=> LL-4243 (Onboarding): fix some vertical scrolling issue

src/locales/en/common.json, src/screens/SendFunds/04-Summary.js
https://ledgerhq.atlassian.net/browse/LL-3631
=> LL-3631 add refill token info box

README.md, docs/linking.md, docs/theming.md
Add theming documentation
Documentation
=> add theming doc

src/components/CameraScreen/QRCodeBottomLayer.js, src/components/InfoBox.js, src/components/PasswordInput.js, src/components/Switch.js, src/components/TextInput.ios.js, src/context/AuthPass/AuthScreen.js, src/index.js, src/screens/Onboarding/shared/infoPagesData.js, src/screens/SendFunds/04-Summary.js, src/screens/SendFunds/AmountInput.js, src/screens/Settings/PoweredByLedger.js, src/screens/WalletConnect/Connect.js
(Dark mode): remaining issue fixes
UI Polish
LL-4461
See ticket for the list of fixes
=> LL-4461 (Dark mode): remaining issue fixes

src/components/Carousel/index.js
Feature
https://ledgerhq.atlassian.net/browse/LL-4532
- Open the app
- Make sure the banner is not present
=> LL-4532 Remove backup pack banner

Gemfile.lock, ios/Podfile.lock, src/components/AccountCard.js, src/components/SelectableAccountsList.js, src/screens/AddAccounts/03-Accounts.js
https://ledgerhq.atlassian.net/browse/LL-4237
=> LL-4237 display full balance on add account selection

src/components/OnboardingStepperView/OnboardingInfoModal.js, src/components/OnboardingStepperView/OnboardingStepView.js
(Onboarding): bullet text line height updated
+ fix bullet icon color issue
UI Polish
LL-4292 LL-4456
Onboarding steps with bullet info
=> LL-4292 LL-4456 (Onboarding): bullet text line height updated

src/locales/en/common.json
Small typo
Fix
LL-4293
Onboarding
=> LL-4293 fix typo on onboarding

src/components/FirstLetterIcon.js, src/families/cosmos/ClaimRewardsFlow/02-SelectMethod.js, src/families/cosmos/shared/Item.js
(FirstLetterIcon): fix potential name missing error causing crash
Bug fix
slack report
=> (FirstLetterIcon): fix potential name missing error causing crash

src/screens/Account/LendingBanners.js
(Lending): fix undefined crash issue whe balance is 0
Bug fix
LL-4639
Opening lending from an account with a balance of 0 DAI should not crash anymore
=> LL-4639 (Lending) crash issue

src/components/accountSyncRefreshControl.js
Bug Fix
LL-4509
Account page spinner when pull to refresh
https://user-images.githubusercontent.com/671786/109841698-9b9ac380-7c49-11eb-813d-8ad11af09925.MP4
=> LL-4509 Fix spinner on account screen

src/families/polkadot/TransactionConfirmFields.js
BugFix
https://ledgerhq.atlassian.net/browse/LL-4684
=> [LL-4684] DOT remove fee fields confirmation

src/families/polkadot/BondFlow/index.js, src/families/polkadot/NominateFlow/index.js, src/families/polkadot/RebondFlow/index.js, src/families/polkadot/SimpleOperationFlow/index.js, src/families/polkadot/UnbondFlow/index.js
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-4685
=> [LL-4685] DOT: Remove CTA navigation on error

src/components/OnboardingStepperView/OnboardingInfoModal.js
(Onboarding): fix font style in help modal desc
UI Polish
LL-4290
Onboarding help modal descriptions should no longer be bold
=> LL-4290 (Onboarding): fix font style in help modal desc

src/components/DeviceAction/index.js, src/components/DeviceAction/rendering.js, src/components/DeviceActionModal.js, src/languages.js, src/screens/Onboarding/steps/terms.js, src/screens/ReceiveFunds/02-ConnectDevice.js, src/screens/ReceiveFunds/03-Confirmation.js
(DeviceAction): fix warning react state update issues
Code Quality Improvement
LL-4457
DeviceAction + some part in the receive flow
=> LL-4457 LLM - Error thrown on add account modal

src/screens/Exchange/coinifyConfig.js
https://ledgerhq.atlassian.net/browse/LL-4585
=> LL-4585 - Add buy coins

src/locales/en/common.json
https://ledgerhq.atlassian.net/browse/LL-4754
=> LL-4754 - no more oops

src/components/BottomModal.js
(Manager): filter modal auto-closing issue
Bug fix
[Ll-4972]
Manager filter modal should open and close correctly now
=> LL-4972 (Manager): filter modal auto-closing issue

src/reducers/settings.js
fix flattenedSwapSupportedCurrenciesSelector issue
Bug fix
Accounts should no longer crash
=> fix flattenedSwapSupportedCurrenciesSelector issue

index.js, package.json, src/screens/NotificationCenter/NewsRow.js, yarn.lock
(NotificationCenter): fix link issue
Bug fix
[LL-5184]
Notifications link should work now
[LL-5184]: https://ledgerhq.atlassian.net/browse/LL-5184
=> LL-5184 (NotificationCenter): fix link issue

src/locales/en/common.json, src/screens/AddAccounts/03-Accounts.js
(Chain type): updated wording
wording
[LL-5072]
Add account bitcoin family -> add new account -> info regarding address type should be updated
[LL-5072]: https://ledgerhq.atlassian.net/browse/LL-5072
=> LL-5072 (Chain type): updated wording

src/config/urls.js
(NotificationCenter): change status help link url
Fix
[LL-5122]
Notification center > status tab > help url updated
[LL-5122]: https://ledgerhq.atlassian.net/browse/LL-5122
=> LL-5122 (NotificationCenter): change status help link url

src/screens/Manager/AppsList/AppInstallButton.js
(Manager): use manager api function to check if an app can be installed
this needs live-common bump https://github.com/LedgerHQ/ledger-live-common/pull/1112
Feature
[LL-4840]
Manager list of apps.
Some apps should no longer be installable
[LL-4840]: https://ledgerhq.atlassian.net/browse/LL-4840
=> Ll-4840 Manager - some apps should only be uninstallable

index.js, src/components/GenericErrorView.js, src/locales/en/common.json, src/log-report.js, src/screens/DebugLogs.js
https://ledgerhq.atlassian.net/browse/LL-4626
Retrieve last N log in mobile app.
Currently, just for demo, I display the last N log when the button "Display latest logs" button is clicked in "Debug Logs" page.
But this logic can be integrated into any other place in the app
=> LL-4626 - Add the possibility to retrieve latest log in mobile app

package.json, yarn.lock
- https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.3.0
- https://github.com/LedgerHQ/ledger-live-common/releases/tag/v19.4.0
- minor upgrade of some deps
=> bump live-common to 19.4.0

src/components/InfoBox.js, src/components/OnboardingStepperView/OnboardingInfoModal.js, src/components/OnboardingStepperView/OnboardingStepView.js, src/config/urls.js, src/locales/en/common.json, src/screens/Onboarding/shared/RecoveryPhraseWarning.js, src/screens/Onboarding/shared/infoPagesData.js, src/screens/Onboarding/steps/useCaseSelection.js
(Onboarding): add recovery phrase warning
UI Polish
[LL-5170]
Onboarding > Select device > select use case should show a warning regarding recovery phrase
[LL-5170]: https://ledgerhq.atlassian.net/browse/LL-5170
=> LL-5170 (Onboarding): add recovery phrase warning

src/screens/Exchange/coinifyConfig.js
https://ledgerhq.atlassian.net/browse/LL-4859
=> LL-4859 - remove dash from coinify buy

src/screens/ReceiveFunds/02-ConnectDevice.js, src/screens/ReceiveFunds/03-Confirmation.js, src/screens/SendFunds/02-SelectRecipient.js, src/screens/SendFunds/03-Amount.js, src/screens/SendFunds/04-Summary.js, src/screens/SendFunds/07-ValidationError.js, src/screens/SendFunds/07-ValidationSuccess.js
(Analytics): add currencyName to send/receive flow page events
Analytics
[LL-5306]
Receive and Send flow page events should have currencyName in the analytics even properties
[LL-5306]: https://ledgerhq.atlassian.net/browse/LL-5306
=> LL-5306 (Analytics): add currencyName to send/receive flow page events

src/screens/ReceiveFunds/03-Confirmation.js
https://ledgerhq.atlassian.net/browse/LL-5078
=> LL-5078 - fix receive qr code on dark theme

src/locales/en/common.json, src/modals/Create.js
https://ledgerhq.atlassian.net/browse/LL-5245
=> LL-5245 - fix lending title in transfer bottom modal

src/screens/NotificationCenter/Status.js
https://ledgerhq.atlassian.net/browse/LL-5267
=> LL-5267 - fix flatlist scroll on status informations

src/families/cosmos/ClaimRewardsFlow/02-SelectMethod.js
Bugfix
https://ledgerhq.atlassian.net/browse/LL-4594
Cosmos display error for claim reward
=> [LL-4594] cosmos: display error on claim reward

src/screens/Accounts/AccountRow.js
UI Polish
https://ledgerhq.atlassian.net/browse/LL-5207
Accounts index
=> [[LL-5207] add tag for derivation mode

src/components/BottomModal.js, src/screens/Manager/AppsList/AppInstallButton.js, src/screens/Settings/Experimental/ExperimentalHeader.js
(Manager + Experimental UI): fix some ui bottlenecks mainly caused by animation nodes unnecessary but that were still kept in the layout -> use some over component for button and wall out experimental header if not needed
=> (Manager + Experimental UI): fix some ui bottlenecks 

src/components/AccountGraphCard.js, src/components/AssetGraphCard.js, src/components/GraphCard.js
https://ledgerhq.atlassian.net/browse/LL-5559
I replaced d.value by NaN and it reproduced the same stacktrace as on sentry. So I supposed I targeted the correct lines.
However it feels like I am not fixing the root cause (having NaN/null as values). but at least it fix the crash.
=> LL-5559 - fix android graph crash

src/screens/PairDevices/index.js
(Pair device): fix ui regression with name + genuine check status after pairing
=> (Pair device): fix name missing + genuine check status

src/screens/Manager/AppsList/AppRow.js, src/screens/Manager/AppsList/index.js, src/screens/Manager/AppsScreen.js, src/screens/Manager/Manager.js, src/screens/Manager/Modals/SearchModal.js
(Manager): optimistic state memoized for out of memory info
=> (Manager): optimistic state memoized

src/components/WebPlatformPlayer/index.js
This PR fixes https://ledgerhq.atlassian.net/browse/LL-5846 android performance issue on recent platform feature.
=> Fixes LL-5846

src/locales/en/common.json
https://ledgerhq.atlassian.net/browse/LL-5870
=> LL 5870 - typo

src/locales/en/common.json
(Wording): allow manager error wording updated
Wording
[LL-5560]
Allow manager warning updated
[LL-5560]: https://ledgerhq.atlassian.net/browse/LL-5560
=> LL-5560 (Wording): allow manager error wording updated

src/screens/Exchange/CoinifyWidget.js, src/screens/Exchange/coinifyConfig.js
https://ledgerhq.atlassian.net/browse/LL-4894
=> LL-4894 - change coinify partnerid

ios/ledgerlivemobile.xcodeproj/project.pbxproj, src/locales/en/common.json, src/screens/Swap/FormOrHistory/History/index.js
Feature
https://ledgerhq.atlassian.net/browse/LL-3449
-  Launch LLM on data that does have swap history, compare to the screenshot.
-  It should not show if there are no operations.
=> LL-3449 (Swap/History) Add warning about swaps not being synced

src/screens/Account/TokenContractAddress.js, src/screens/OperationDetails/Footer.js, src/screens/OperationDetails/index.js
add tracking to View in Explorer action
improvement
LL-6087
view in explorer actions now trigger a tracking
=> LL-6087 add tracking to view in explorer

package.json, yarn.lock
includes: 
- https://github.com/LedgerHQ/ledger-live-common/pull/1304
- https://github.com/LedgerHQ/ledger-live-common/pull/1305
=> bump live-common

package.json, yarn.lock
=> live-common 20.8.0

package.json, yarn.lock
Bumping LLC to include Lido dapp
LL-6376
Catalog
=> bumped LLC to include lido release

src/components/CheckBox.js, src/locales/en/common.json, src/screens/Platform/DAppDisclaimer.js, src/screens/Platform/index.js
We should not be able to open a DApp without consenting to the disclaimer. Disclaimer can be accepted once or dismissed forever for all DApps.
<details>
<summary>iOS 📸 </summary>
https://user-images.githubusercontent.com/86959861/125981848-6d04ca2e-e49e-47b6-a25f-ee51a1887f3c.mp4
</details>
<details>
<summary>Android 📸 </summary>
https://user-images.githubusercontent.com/86959861/125981882-48e9652b-3e86-41d6-8d7f-0038cae69cf0.mp4
</details>
Feature
[LL-6423](https://ledgerhq.atlassian.net/browse/LL-6423)
Platform -> Press on any DApp
=> LL-6423 - Add Platform DApp disclaimer

src/screens/SendFunds/04-Summary.js
Bug Fix
[LL-6598](https://ledgerhq.atlassian.net/browse/LL-6598)
=> LL-6598 Hide buy button when currency isn't supported on send flow 

src/logger.js
see https://github.com/getsentry/sentry-javascript/issues/2292
=> don't reportError if it's not instance of error

src/screens/EditDeviceName.js
(EditDeviceName): lower MAX_DEVICE_NAME from 32 to 20
Feature
[LL-5935]
Manager > Edit device name
[LL-5935]: https://ledgerhq.atlassian.net/browse/LL-5935
=> LL-5935 (EditDeviceName): lower MAX_DEVICE_NAME from 32 to 20

src/context/AuthPass/index.js
https://ledgerhq.atlassian.net/browse/LL-6776
=> LL-6776 - authpass on top of everything

package.json, yarn.lock
=> update LLC to 21.3.0

src/experimental.js
https://ledgerhq.atlassian.net/browse/LL-6702
needs LedgerHQ/ledger-live-common#1174
=> LL-6702 - tezos js impl exp

src/index.js, src/navigation/useDeepLinking.js, src/screens/NotificationCenter/NotificationsProvider.js
https://user-images.githubusercontent.com/89014981/131482792-d5df9531-53e9-4a24-a8f1-72751363fb64.mp4
https://user-images.githubusercontent.com/89014981/131482800-1221f3ed-59ab-4622-a171-0bfe99dc6769.mp4
Feature
https://ledgerhq.atlassian.net/browse/LL-6403
All deep links :
- Deep links inside notifications
-  Deep links outside application (eg: Clicking link on Chrome)
=> LL-6403 Add deep linking for settings + fix mock notification

ios/Podfile.lock, src/config/urls.js
https://ledgerhq.atlassian.net/browse/LL-6899
only one link matched and one link with a question so i did not change anything
=> LL-6899 - links

contributor.md
=> add elrond team as a contributor

package.json, yarn.lock
https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.4.2
live-common bump
https://ledgerhq.atlassian.net/browse/LL-7289
noop impact
=> Update live-common to 21.4.2

src/components/DeviceActionModal.js, src/locales/en/common.json
https://ledgerhq.atlassian.net/browse/LL-5851
=> LL-5851 - add infobox to device action modal

src/live-common-setup.js
https://ledgerhq.atlassian.net/browse/LL-6157
=> LL-6157 - remove stratis from supported currencies

src/experimental.js
qa / dev requirement
https://ledgerhq.atlassian.net/browse/LL-5862
experimental settings , countervalues
=> Add Countervalues API experimental env

src/components/WebPlatformPlayer/InfoPanel.js
UI Polish
[LL-7315]
[LL-7315]: https://ledgerhq.atlassian.net/browse/LL-7315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-7315 Fix contrast of text colors in WebPlatformPlayer/InfoPanel

src/screens/Manager/AppsList/AppUpdateAll.js, src/screens/Manager/Modals/UpdateAllModal.js
Rename property listing names of the apps updated when clicking update all button in manager
Fix
https://ledgerhq.atlassian.net/jira/software/c/projects/LL/boards/277?modal=detail&selectedIssue=LL-7219&sprint=770
=> LL-7219 - Rename updateAll event property appsList to appName

src/languages.js
- LL-7680 (Languages): activate de
Feature
[LL-7680]
Languages should have german available as an option
[LL-7680]: https://ledgerhq.atlassian.net/browse/LL-7680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-7680 (Languages): activate de

src/screens/Exchange/CoinifyWidget.js
- LL-7197 (BUY): analytics - track payment method
Track payment method after a succesfull buy order been placed
Feature
[LL-7197]
Analytics after a successfull buy should hold medium data (payment method)
[LL-7197]: https://ledgerhq.atlassian.net/browse/LL-7197
=> LL-7197 Buy - analytics

src/components/TranslatedError.js, src/locales/en/common.json
Jira ticket
https://ledgerhq.atlassian.net/browse/LL-5221
Android Nano S
Android Nano X
IOS Nano S (For Nano X, it is similar)
=> fix error wording for different device/platform

src/index.js
=> Fix instant crash caused by react navigation v6

src/components/Scanner.js
Fix crash when importing accounts via QR code.
Bug Fix
[LL-7898](https://ledgerhq.atlassian.net/browse/LL-7898?atlOrigin=eyJpIjoiYzc1YTc0ZDUzNjlmNGQ0NWI2OGI5NDg5OWM2ZjdjYjUiLCJwIjoiaiJ9)
Import Account
=> LL-7898 Fix useNavigation import path

docs/linking.md
- LL-6884 (Deeplinks): updated documentation
[LL-6884]
[LL-6884]: https://ledgerhq.atlassian.net/browse/LL-6884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-6884 Deeplink doc

src/screens/Swap2/FormSelection/AccountAmountRow.js, src/screens/Swap2/FormSelection/CurrencyTargetSelect.js
[LL-7843]
Feature
<details>
<summary>Screen</summary>
</details>
[LL-7843]: https://ledgerhq.atlassian.net/browse/LL-7843?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-7843 - SWAP - Make target amount 'responsive'

src/screens/AddAccounts/01-SelectCrypto.js, src/screens/Exchange/SelectCurrency.js, src/screens/Manager/Modals/SearchModal.js
exactly the same as https://github.com/LedgerHQ/ledger-live-desktop/pull/4437
=> LL-8172  hide tokens which have their parent currency disabled

package.json, src/components/BottomModal.tsx, yarn.lock
Integrate the rebranded version of the bottom drawer.
https://user-images.githubusercontent.com/91940736/142014951-53351581-d2a5-44ba-bd38-7ed62370d097.mov
[LL-8034]
[LL-8034]: https://ledgerhq.atlassian.net/browse/LL-8034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8034 Rebranding of the bottom modal and bump native ui library version

package.json, src/components/RootNavigator/MainNavigator.js, src/components/RootNavigator/ManagerNavigator.js, src/components/TabIcon.tsx, src/screens/Portfolio/TabIcon.tsx, src/screens/Transfer.js, yarn.lock
Rebranding
[LL-7745]
[LL-7745]: https://ledgerhq.atlassian.net/browse/LL-7745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-7745 - navigation footer rebrand

src/components/Button.tsx
Clean the `<Button />` proxy component.
UI
[LL-8035]
[LL-8035]: https://ledgerhq.atlassian.net/browse/LL-8035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8035 - Rebrand - Button

src/components/RootNavigator/AccountSettingsNavigator.js
Bug Fix
[LL-8217]
[LL-8217]: https://ledgerhq.atlassian.net/browse/LL-8217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8217 - fix(router): add accounts route to AccountSettingsNavigator

src/components/AnimatedHeader.js, src/components/FabActions.js, src/components/RootNavigator/AccountSettingsNavigator.js, src/screens/Portfolio/index.js
=> ENGB2C-115 Bug fixes

src/languages.js
- (Languages): deactivate de for now
Bug fix
[LL-8270]
[LL-8270]: https://ledgerhq.atlassian.net/browse/LL-8270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8270 deactivate de

src/screens/AccountSettings/index.js, src/screens/Onboarding/steps/finish.js
fix issue in allocation delete account navigation
Bug Fix
[LL-8217]
[LL-8217]: https://ledgerhq.atlassian.net/browse/LL-8217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8217 (AssetAllocation): fix navigation issue

src/components/CurrencyInput.js, src/components/FocusedTextInput.js, src/components/PasswordInput.js, src/components/TextInput.android.js, src/components/TextInput.ios.js, src/families/algorand/ScreenEditMemoValue.js, src/families/bitcoin/ScreenEditCustomFees.js, src/families/cosmos/EditMemo.js, src/families/ethereum/ScreenEditGasLimit.js, src/families/ripple/ScreenEditTag.js, src/families/stellar/ScreenEditMemoValue.js, src/screens/Settings/About/DescriptionRow.js
- (TextInput): created a wrapped input that handles autofocus all the time
Bug fix
[LL-8308]
All text inputs should be wrapped arround a native input that handles autofocus on mount + dispatches ref correctly
[LL-8287]: https://ledgerhq.atlassian.net/browse/LL-8287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LL-8308]: https://ledgerhq.atlassian.net/browse/LL-8308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8308 (TextInput): fix autofocus

src/components/KeyboardView.js
Bug Fix
[LL-7282]
[LL-7282]: https://ledgerhq.atlassian.net/browse/LL-7282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-7282 - Fix keyboard behavior

src/locales/en/common.json, src/screens/Onboarding/OnboardingView.tsx, src/screens/Onboarding/steps/useCaseSelection.tsx
**Blocked by the release [(`native/0.5.0`)](https://github.com/LedgerHQ/ui/tags) of ui** ⚠️ 
UI Polish
[LL-7749] 
[LL-7749]: https://ledgerhq.atlassian.net/browse/LL-7749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-7749 - V3 - Onboarding - Flow selection

package.json, yarn.lock
fixes of https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.19.1
=> update live-common with NFT fixes

src/components/RootNavigator/NotificationCenterNavigator.tsx, src/screens/NotificationCenter/News.tsx, src/screens/NotificationCenter/NewsRow.tsx, src/screens/NotificationCenter/Snackbar/Snackbar.tsx, src/screens/NotificationCenter/Status.tsx
Merge https://github.com/LedgerHQ/ui/pull/103 before :warning: 
https://user-images.githubusercontent.com/89014981/143271355-38b9362e-9708-42aa-ad02-28889f33bfc5.mp4
https://www.figma.com/file/uQYdD0E0ELDKi3skrduZpw/LLM-%2F-Notification-Center?node-id=3%3A9
Rebranding
[LL-8031]
Notification center / Snackbar
[LL-8031]: https://ledgerhq.atlassian.net/browse/LL-8031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LL-8031 - Rebranding - Notification center

package.json, yarn.lock
bump live-common
[
](https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.23.0)
=> Update live-common 21.23.0

src/screens/Manager/index.js
=> only go to device page if success

package.json, yarn.lock
Bug fix
https://github.com/LedgerHQ/ledger-live-mobile/pull/2143
=> LL-8926: Fix polkadot bigInt issue

package.json, yarn.lock
I forgot to do it for my previous PR which had a (non breaking) dependency on this version 😬 
https://github.com/LedgerHQ/ledger-live-mobile/pull/2260
=> Upgrade UI lib to 0.7.3

src/components/DeviceAction/getDeviceAnimation.js
Bugfix
https://ledgerhq.atlassian.net/browse/LIVE-1748
- Start the app using a proxy device
- Try accessing the manager with that device
- See if it crashes or not, it shouldn't!
=> LIVE-1748 Prevent crash when using proxy device
