package.json
src/actions/counterValues.js
src/components/CounterValuePolling.js
src/components/NetworkIndicator.js
src/index.js
src/screens/Dashboard/Header.js
src/screens/Dashboard/index.js
src/screens/ImportAccounts.js
yarn.lock

- some bugfixes in wallet-common regarding the countervalue api https://github.com/LedgerHQ/ledger-wallet-common/commit/5e7a064c336175aa0f43e351a4100cd62c0cc83c
- refactor countervalues to adopt unified pollRates() (see draft proposal)
- make app working offline, before it was always waiting countervalues to load..
- add a generic CounterValuePollingProvider & withCounterValuePolling
- code from Root was migrated in the provider. it have the same autopolling feature / listen to appstate like before. however, it only happens when root is "ready", which is when localstorage is asynchronously read (in the future it is important if we decrypt it)
- counterValuePolling.poll() method is exposed via context, and returns a Promise (we have used it in the "pull to refresh" of dashboard just for …

coutervalues refactoring, making app working offline

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

Fixed by rolling back Gradle and its Android plugin to the highest version compatible with React Native, and prevent them to try to use a dropped architecture toolchain.
- Android Studio uses the latest NDK version (with no way to force a lower version from the build config files)
- The latest NDK version dropped MIPS support
- Only the latest Gradle Android plugin take that into account
- React Native isn't compatible with the latest Gradle Android plugin
- or even the latest Gradle version
cf android-ndk/ndk#700

Fix staging and release builds on Android

---

src/colors.js
src/components/Menu.js
src/components/ModalBottomAction.js
src/config/urls.js
src/images/icons/ExternalLink.js
src/images/icons/Warning.js
src/locales/en/common.json
src/screens/Settings/Help/ClearCacheRow.js
src/screens/Settings/Help/ExportLogsRow.js
src/screens/Settings/Help/HardResetRow.js
src/screens/Settings/Help/LedgerSupportRow.js
src/screens/Settings/Help/index.js

1) UI for Help section in Settings.
2) Ledger Support Row is functional and it is an external link
3) Hard reset is functional -> it brings a warning modal and resets the app on click
Help Section            |  Hard Reset Modal
:-------------------------:|:-------------------------:
Tested on iPhoneX and Android emulator

settings help section, hard reset, support

---

src/components/GenericButton.js
src/components/ModalBottomAction.js
src/images/icons/Trash.js
src/locales/en/common.json
src/screens/Settings/Help/ClearCacheRow.js
src/screens/Settings/Help/HardResetRow.js

To accommodate designs bottom modal drawer was updated (now used just in hard reset and clear cache). it was also generalized to be able to update it if needed easier in the future if needed.
Tested on iPhone X, on simulators: iPhone SE and iPhone 6+ and on the android simulator
Hard reset           |  Clear cache
:-------------------------:|:-------------------------:

update bottom modals for design and make more generic for future

---

src/polyfill.js

This was causing a throw when running on jest.

Prevent polyfill call in test environment

---

android/app/build.gradle
android/build.gradle
package.json
yarn.lock

Use [npm/jsc-android](https://www.npmjs.com/package/jsc-android) which is up to date, in place of the 4 year old build of JSC bundled with React Native.
I did a quick test on our app, and it seems to give a nice performance boost.

 JavaScriptCore upgrade for Android

---

src/components/CurrencyIcon.js

we can improve the fallback but we probably need one because in future when ERC20 will be there, we won't have icons for all.

Implement a fallback when no crypto icons

---

src/locales/en/common.json
src/navigators.js
src/screens/Settings/Currencies/CurrencySettings.js
src/screens/Settings/Currencies/index.js
src/screens/Settings/index.js

Currency Settings according to the new design 
1) When we have more than 1 currency - we have now intermediary screen with a list of currencies, each clickable with navigation to another string with settings (conf number and exchange if applicable)
2) if we have just 1 coin it goes straight to the Settings page without rendering the list first
TODO: add icon in the dynamic title and maybe place current value of slider in a different place
<div>
</div>

currency settings re-design

---

src/components/Delta.js
src/components/FormatDate.js
src/components/provideSummary.js
src/locales/en/common.json
src/screens/Portfolio/AnimatedTopBar.js
src/screens/Portfolio/PortfolioGraphCard.js
src/screens/Portfolio/index.js

Two features in this commit:
- add scroll-based-animated top bar in Portfolio screen. It displays total balance.
- when touching the graph, the date is shown on the card header

Portfolio animated top bar & Graph improvements

---

src/components/Graph/index.js
src/components/GraphCard.js
src/screens/Portfolio/index.js

Following discussions about the usefulness of the actual graph (e.g https://github.com/LedgerHQ/ledger-live-desktop/issues/1478), the `Graph` component can now renders either countervalues or directly values. I've changed the curve to be square-based, because it makes no sense to interpolate here, and enabled it on account screen (Portfolio screen mixes all crypto, so not doable).
IMO (also asked multiple times on desktop), Portfolio **should not display line graph** but a **pie chart** showing % of holding of each asset based on cv. Again, mixing up market prices + transaction history makes no sense.

Graph ability to draw based on value instead of countervalue

---

package.json
src/navigators.js
yarn.lock

Couldn't find a way to style it like described in the docs (just using `style` prop in parameters), so I took the second docs example, using `react-navigation-tabs`. Works like a charm and we can customize what we want.

Update main tab bar style

---

ios/ledgerlivemobile/Info.plist
src/components/AuthFailedApp.js
src/components/AuthPendingApp.js
src/components/HardResetModal.js
src/locales/en/common.json
src/screens/Settings/Help/HardResetRow.js

Face ID for X integrated. I tested also with Touch ID for iOS 7 and fingerprint option on Android Simulator (we will need a decision on older devices that don't support biometrics).
FaceID and TouchID both fallback on native PIN.
This PR has a temp UI for re-trying or reseting the app. 
In the following weeks we have to have some meeting on all possible behaviors and approach we take with Privacy. 
1 | 2 | 3 | 4 | 5 | 6 | 7
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------

face id integration with fallback screen

---

android/app/build.gradle
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ledgerlivemobile/MainApplication.java
android/settings.gradle
ios/ledgerlivemobile.xcodeproj/project.pbxproj
package.json
src/logic/getLibcore.js
src/logic/libcore.js
src/polyfill.js
yarn.lock

- new dependency on `lib-ledger-core-react-native-bindings`
- load the dynamic library at runtime
- get the `core` cross-platform singleton from `logic/getLibcore.js`, which init the wallet pool instance and a bunch of implementations (http handler, logger..) and exposes our native methods
- add a basic bitcoin account sync from xpub POC in `helpers/libcore.js`
- add a little hack to prevent (showing) error from double promise callback call on libcore side (see `src/polyfill.js`)
I have only tested it on Android, the iOS native methods still needs to be mapped in `logic/getLibcore.js`, if I remember the generated names are different so @KhalilBellakrid  we'll need you to point us the direction where to search :)
Anyway, the whole thing should work out of the box with only a `yarn …

Libcore integration for Android & iOS

---

src/constants.js
src/logic/accountId.js
src/logic/accountName.js
src/logic/getLibcore.js
src/logic/libcore.js

Except a few fields (e.g: `blockHeight`), the builded object is ISO as desktop :ok_hand:

Build Account from coreAccount

---

src/components/Graph/index.js

In some cases the `cuveCatmullRom` causes strange behaviour (e.g going under `0` because of curving). `curveBasis` is not perfect also, because the "dot" following the finger end up not in the line. Let's step back to `curveLinear` (ISO as desktop)
catmullRom | curveBasis | curveLinear
------------ | ------------- | ---------

Use linear curve for portfolio graph

---

.circleci/config.yml
package.json

With this, we can call `yarn ci` and run prettier, lint, flow and the integrity check for dependencies in case we haven't run `yarn` in a while to avoid pushing an outdated lock, left the `test` reference regardless of it being a placeholder for now.

Added the `ci` command for yarn, with the added integrity check

---

src/locales/en/common.json
src/screens/AccountSettings/EditAccountName.js
src/screens/AccountSettings/EditAccountNode.js
src/screens/AccountSettings/EditAccountUnits.js
src/screens/Settings/Currencies/CurrencySettings.js
src/screens/Settings/General/RateProviderSettings.js
src/screens/makeGenericSelectScreen.js

Although the original bug report (by me) focused on the account name as the only odd behavior, we decided to remove the X button on all secondary account settings screens since they'd go away from the flow completely.
Hopefully, this makes more sense.

Removed the right X navigation button from some secondary screens

---

src/screens/SendFunds/01-SelectAccount.js

To be consistent with what happens if you go to a specific account with no funds (only receive action is available), we should filter the accounts displayed on the select account screen for send flow.

LL-942 Filtered out empty accounts

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/res/xml/usb_device_filter.xml

On the current develop version of the app, the experimental usb connections request user permission to access the connected device *everytime we want to interact with it*, meaning that if we disconnect the device and go to the manager again it will once again request user confirmation to access the device. The checkbox provided on that dialog seems to be ignored.
By setting an `intent-filter` on our activity that listens to the `USB_DEVICE_ATTACHED` event for a list of vendorId/productId pairs we can request the user to set Ledger Live Mobile as the default app when plugging in (and unlocking) the device, allowing us to skip the permission request when trying to interact with it.
It's a quick win that makes the ux better.

LL-993 Added intent-filter to allow handling ledger devices via USB OTG

---

src/components/SelectDevice/index.js
src/screens/Onboarding/steps/pair-new.js

the pairing flow should only be for the ble devices (not the other transports like http proxy, usb, etc.)
bug fix
that BLE pairing still works, that you can also still see "already paired" device in the list.

Make the pairing screen only strictly for BLE transport

---

README.md
src/locales/en/common.json
src/screens/ReceiveFunds/02-ConnectDevice.js
src/screens/ReceiveFunds/NotSyncedWarning.js

This should only apply to accounts imported from desktop that haven't had a chance to sync with their corresponding blockchains. Moreso, it's apparently only affecting bitcoin family coins since we won't necessarily have a `freshAddress` ready in the code.
To test:
- Import accounts from desktop and make the phone unable to sync
- Go to a certain account and try to receive funds
- See this
Known issue: If you are in airplane mode and the sync _fails_ you will be left in that screen forever, you'd need to refresh on the main screen for the sync to resume. So maybe address that in a future release

Added failsafe screen for non-synced imported accounts

---

src/components/RequiresBLE/RequiresLocationOnAndroid.android.js

On Android, after being prompted to allow the location permission **and rejecting it** the app will insta-crash when clicking on _Pair new device_, the reasoning for this is that after an initial permission request that we reject, the app tries to use the `rationale`.
The `rationale` we provide is a title and a message that we were passing as jsx, and that was chocking the `PermissionsAndroid` logic. Throwing a seemingly unrelated error for `nativeFlushQueueImmediate` at the c++ level but that I guess was triggered when the `request` method was passing that stuff around.
I removed the rationale from our code since it was showing an ugly dialog (no styles, no dismiss) that shows the same information that our specific screen for "Location Required". Without that, since we aren't passing the …

LL-1022 [Android] Fix retry crash after rejected permissions

---

src/components/StepHeader.js
src/locales/en/common.json
src/screens/Account/AccountHeaderTitle.js

Updated the copy for readonly mode account confirmation, with a new text from @dasilvarosa and some styling for the account titles that were getting chopped on iPhone SE. Hopefully, this makes it better.

LL-954 Modified copy for Readonlymode confirmation, adjusted styles for account titles

---

src/components/SettingsRow.js
src/screens/Account/index.js
src/screens/AccountSettings/EditAccountName.js
src/screens/Accounts/AccountRow.js
src/screens/Accounts/index.js

Augment the max number of character for the account name to 50 (to be iso with desktop) and fixed SettingsRow to accept longer name
feat + fix
LL-951 LL-952
EditAccountName, Accounts page

fix account name length + ui fixes

---

src/locales/en/common.json
src/screens/ImportAccounts/DisplayResult.js
src/screens/ImportAccounts/DisplayResultItem.js
src/screens/ImportAccounts/DisplayResultSettingsSection.js
src/screens/ImportAccounts/ResultSection.js

This ads the posibility to retry after scanning the LiveQR Code from desktop or to import simply the settings in the case of not having accounts to import. It initially didn't have the retry cta, hence the comments below mentioning the need to reword.

LL-968 Allow user to finish onboarding with an empty import

---

src/components/SettingsRow.js
src/screens/AccountSettings/AccountNameRow.js

A past fix for Account name length brought in a regression into all settings row (Settings/General for example). The solution is to not center the elements of the row inside but rather space them, and a few more tweaks. This limits the right content to a max of 50% too, so it never squeezes the left either.

Fixed a regression in SettingsRow

---

package.json
src/families/bitcoin/ScreenEditFeePerByte/CustomFeesRow.js
src/families/bitcoin/ScreenEditFeePerByte/index.js
src/locales/en/common.json
yarn.lock

Disabled the button and show an error when 0 fees are entered in the custom fees for bitcoin family. **Updated** with the latest design from @bscholving which always shows the warning and will turn red on invalid input, updated wording too.

LL-1028 Added block to 0 fees

---

src/components/Installing.js
src/components/behaviour/SkipLock.js
src/constants.js
src/context/AuthPass/index.js
src/screens/Manager/AppAction.js
src/screens/ReceiveFunds/03-Confirmation.js
src/screens/SendFunds/06-Validation.js
src/screens/Settings/Debug/index.js

Created a `<SkipLock/>` component that will allow us to disable the autolock behaviour in certain parts of the application to avoid breaking a flow or disturbing a process that requires the app to be inactive (pairing for example could also get this if wanted).
To use it simply render the component in the screen you want to disable autolock for.
Autolock should be disabled while installing an app, updating firmware, or validating data on the device. To test, simply navigate out of the app while on one of those screens, wait 1 minute (or modify the environmental variable to a lower setting) and come back to the app.

LL-1051 Created SkipLock component to disable auto-lock in certain processes

---

package.json
src/components/CameraScreen/QRCodeBottomLayer.js
src/logic/getWindowDimensions.android.js
src/logic/getWindowDimensions.ios.js
yarn.lock

This one was a bit trippy for me because when I looked into the library we are using for the so-called extra dimensions's [readme](https://github.com/Sunhat/react-native-extra-dimensions-android) it looks like the guy was not paying much attention to the names of the helper methods with names such as `getRealWidthHeight`, [created a pr to help](https://github.com/Sunhat/react-native-extra-dimensions-android/pull/44) 🕺. In any case, what happens is that sometimes we will have a soft menu bar on that screen and we can add padding to the styles to account for it.
On other devices without the bar shown the padding is not added.
Here's an inception photo (screen capture of a Huawei p10 looking at the emulator for a pixel XL) to illustrate.

LL-1021 Take into account `softmenubarheight` on account scan

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ledger/live/MainActivity.java
android/app/src/main/res/values/styles.xml
src/languages.js
src/screens/OperationDetails/Content.js

On devices (Android) using a right-to-left language such as Arabic or Hebrew, Android enforces a conversion of the layout that breaks the app making it look terrible. 
Common solutions proposed online to disable the rtl conversion seem to not currently work, as a workaround we will detect the locale of the device `onResume` at the native level and enforce the use of `en` instead for rtl languages. iOS seems to not be affected by this and respects the original app's layout instead of enforcing a conversion (kudos apple)
I left a `TODO` in the code for this, but if we ever support a rtl language we'd have to add the exception to the code in order for the translations to actually work, otherwise it will use this and end up with english.

LL-1046 Override detected language if it's RTL

---

.eslintrc
package.json
src/locales/en/common.json
src/screens/EditDeviceName.js
yarn.lock

To prevent characters that can't be displayed on the NanoX screen this adds a filter of non-ASCII characters to the edit device name screen. The behavior is a bit glitchy on Android where it will allow you to enter the character but clean-up only after another character is entered or we try to save. This is an issue with the events triggered on Android, works well on iOS.
Content is sanitized on both platforms. Try entering non-ASCII characters.

LL-1072 Disable input of non ascii character for device name

---

scripts/post.sh
src/bridge/BridgeSyncContext.js
src/index.js
src/libcore/getFeesForTransaction.js
src/libcore/scanAccountsOnDevice.js
src/logger.js
src/screens/FirmwareUpdate/03-MCU.js
src/screens/ImportAccounts/DisplayResult.js
src/screens/Manager/AppsList.js
src/screens/PairDevices/Scanning.js
src/screens/PairDevices/index.js
src/screens/ReceiveFunds/03-Confirmation.js
src/screens/RepairDevice.js
src/screens/SendFunds/06-Validation.js

some errors has been silently because buggy code introduced in #784 . to avoid this in future, we are factorizing this code in `logger.critical` code sample.
this was preventing the genuine check error to display at all! I think there are potentially other spots that was affected by this bug (basically instead of seeing the error, you still see things in pending state)
bug fix

Fixes regression introduced by #784

---

src/context/Locale.js
src/languages.js

Somehow the locales were leaking regardless of the allowed languages, I refactored the languages file and added the `whitelist` param to the init of i18next. This seems to remove the Oui.

Refactored languages, added whitelist

---

package.json
src/components/DeviceJob/index.js
yarn.lock

as soon as the genuine check was done once, it's no longer needed to do again. This is solved by using a flag that the device tell us and not doing genuine check if allow manager was done in the past on that specific device.
also increase the debounce to see less blinks during the steps.
better performance of opening manager & better UX 
https://github.com/LedgerHQ/ledger-live-common/pull/169
manager / genuine check

Add more lazy implementation of genuineCheck (done in live-common)

---

src/reducers/settings.js
src/screens/Manager/ReadOnlyNanoX.js
src/screens/Manager/index.js

Integrated back the readonlymode flag, for iOS.
Should show the pitch nanoX screen for iOS devices until we pair one, should be transparent for Android.

Reintegrated the readonly flag for iOS

---

src/components/CameraScreen/QRCodeBottomLayer.js
src/components/CameraScreen/index.js
src/locales/en/common.json
src/screens/ImportAccounts/Scan.js
src/screens/SendFunds/ScanRecipient.js

Refactored the camera component a bit to allow for both `liveqr` and `normalqr` wording.

LL-1115 Fixed wording for camera import/scan recipient

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
package.json
src/components/CameraScreen/QRCodeBottomLayer.js
src/components/CameraScreen/index.js
src/navigators.js
src/screens/ImportAccounts/Scan.js
src/screens/SendFunds/FallbackCamera/FallbackCameraSend.android.js
src/screens/Settings/General/ConfirmPassword.js
yarn.lock

Had to upgrade the build tools version to allow the new version of `react-native-keychain`, this ideally should fix LL-1123 or at least the part of it pertaining to the fingerprint scanner crashes. ~The camera intent still remains a mystery.~ The camera intent crash was caused by an incorrect import of the fallback camera screen where we were specifying the ios import, hence calling the settings intent with react native's `Linking` instead of the specific android library we use.
Also changed the replace route for the fallback camera screen, apparently we can't replace to a route that's not in the same `StackNavigator` unless it's in `BaseNavigator`

LL-1123 Upgrade react-native-keychain to fix null exception + settings intent crash + wrong redirect

---

src/screens/ReceiveFunds/03-Confirmation.js

Small design change for the receive confirmation screen, moving the two ctas for copy/share to be center aligned instead of spread.

Center ctas on receive screen

---

src/components/DeviceItemSummary.js
src/screens/PairDevices/index.js

if you do a new pairing, the name that might have been set on the device is now also fetched.

Get the device name at pairing time

---

src/constants.js
src/families/bitcoin/ScreenEditFeePerByte/CustomFeesRow.js
src/screens/SendFunds/02-SelectRecipient.js

- fix unlinked clear button on input for the recipient address
- adds a max fee cap to custom fees for bitcoin-like coins

Clear input button on recipient address, send flow, max cap

---

src/components/SettingsRow.js
src/screens/Settings/General/BiometricsRow.js

The biometric icon should be centered regarding the title and description according to design. Note that the text doesn't match because I had to mock the biometric type but the center should still work regardless of the type.

Added a centeredIcon flag for SettingRow icons

---

src/components/OperationRowDate.js
src/context/Locale.js

as the app only supports English at the moment, everything must consistently fallback to English (date and number formatters).
- using Arabic system language was creating bad rendering of our app
- using French system language does not correctly format the price (until we support French)
**before**
**after**
Bug
LL-1196
- Arabic system language is fallbacking to English
- French system language is fallbacking to English
- English system language works like before

Fixes display on phone using a locale not supported

---

src/components/ConfirmationModal.js
src/icons/AlertTriangle.js
src/icons/ExclamationCircle.js
src/locales/en/common.json
src/screens/ReceiveFunds/03-Confirmation.js
src/screens/SendFunds/04-Summary.js

Feature
https://ledgerhq.atlassian.net/browse/LL-1077
The send flow, try to send an amount with fees representing more than 10% of the amount, you should be prompted with the above modal to confirm that unusual transaction. ~~The modal should not be dismissable by clicking outside~~ the user needs to either confirm and go to the next step, or cancel and remain on the first step of the flow.

feat: LL-1077 Add failsafe to the send flow when fees are too high

---

src/screens/ReceiveFunds/03-Confirmation.js
src/screens/SendFunds/02-SelectRecipient.js

When using the v3 explorer for Ethereum get the estimated gas limit from the servers instead of using the hardcoded 21k. This will graciously fallback to the 21k for v2. Note that we will need to set the `USE_EXPERIMENTAL_EXPLORERS` flag programmatically for this to work, or flick the switch in the experimental features screen once it's available.
Feature
https://github.com/LedgerHQ/ledger-live-common/pull/191
Needs to have `live-common` bumped with the code from that pr
Send flow, for Ethereum, try using a contract vs non-contract address, see if the gas limit changes.

feat: LL-1004 Use estimage-gas-limit to prefill gas

---

src/implement-react-native-libcore/loadCoreImpl.js

Bug Fix
After import, apps were crashing due to an incorrect declaration of the getIndex method.

Fixes app to crash with import accounts

---

src/components/DeviceItem.js

Bug fix, refression on paired devices
Pairing devices bluetooth

bugfix: Disable device selection for already paired devices

---

src/locales/en/common.json

Wording
https://ledgerhq.atlassian.net/browse/LL-1223
Add accounts flow, wording has been synced with the one on desktop following the linked issue

LL-1223 Wording changes for add account

---

src/screens/PairDevices/index.js

Addresses the empty device name regression
Regression
LL-1259
Device pairing

LL-1259 fix: Fallback to device name if no custom device name available

---

src/screens/AccountSettings/EditAccountName.js

Prevents users from changing an account's name to an empty string.
UX improvement
https://ledgerhq.atlassian.net/browse/LL-1317
Account edit screen

LL-1317 Trim account name on edition/import

---

src/components/CheckBox.js
src/screens/ImportAccounts/DisplayResultItem.js
src/screens/ImportAccounts/DisplayResultSettingsSection.js

When I did the swipe to edit account name functionality in the wrong place, I also polished the UI of that screen (Import accounts). This simply makes the checkbox check a bit larger, adds a bit of margin to align with the checkbox from the settings import. 
This is more aligned with what's on zpl
UI Polish

UI Polish: used checkbox from design instead of native

---

src/screens/Manager/AppAction.js

Type
Feature
Context
https://ledgerhq.atlassian.net/browse/LL-1306
Parts of the app affected / Test plan
Clicking outside of the modal (in the backdrop) should not close the modal while installing or uninstalling an app. Clicking on the X should still cancel the action

LL-1306 Mobile: prevent backdrop click while installing/uninstalling

---

src/screens/OperationDetails/Content.js
src/screens/PairDevices/index.js

It will also be trimmed if needed, the styles are accounting for that.
UI Polish - Regression
https://ledgerhq.atlassian.net/browse/LL-1319
Operation details
> There is a prettier change to another file that kept being changed to that syntax when I run `yarn prettier` if this is not happening to anyone else perhaps my settings are wrong. If it is... it will no longer happen 🤷‍♂️

LL-1319 Show full precision on operation details

---

src/components/ConfettiParty/index.js
src/screens/Onboarding/steps/finish.js

There is a pretty obvious lag between the `share analytics` step and the `finish` step of the onboarding flow. This made the app seem irresponsive for a few seconds, depending on the speed of your device. I played with a few alternatives like using pngs, prerendering on previous steps, not using svgs, etc but the performance gains were negligible, at least from my vague measurements.
This is a compromise where we will render the page immediately after the user clicks on the button by using `InteractionManager.runAfterInteractions` and then in the background try to do the confetti party without making the app choke. Granted the confetti takes a while to appear, but I'd rather be able to ignore the confetti and Open the app, and be surprised by the confetti if I'm in that screen long enough …

UI Polish Simplified Confetti, alternative approach

---

android/app/src/debug/AndroidManifest.xml

Starting with Android 9.0 (API level 28), cleartext communication is disabled by default, which breaks the plain HTTP connection to the bundler used in dev mode.
This PR allows un-encrypted traffic for the app in dev mode *only*.

Fix connection to bundler on Android (in dev mode)

---

src/screens/OperationDetails/Content.js

Operations details values were showing unnecessary trailing zeroes, this should fix that.

Fix showing to many digits in operation details

---

src/locales/en/common.json
src/locales/es/common.json
src/locales/fr/common.json
src/locales/ja/common.json
src/locales/ko/common.json
src/locales/ru/common.json
src/locales/zh/common.json

The instructions for accessing the LiveQR export on Ledger Live desktop were wrong.
This fix that.
Wording fix
LiveQR import

Fix LiveQR instructions

---

.prettierignore
src/components/BottomModal.js
src/components/DeviceJob/StepRunnerModal.js

For modals that involve device interactions, most of them except notices and warnings, we now have disabled the backdrop and back button dismissals while maintaining the X cta active. This will prevent unwanted dismissals of the modal.
Feature
https://ledgerhq.atlassian.net/browse/LL-1376
All modals.

LL-1376 Prevent bottom modal dismissals for device steps

---

package.json

Since we removed reset from the interface we now have to manually uninstall the app and it's time-consuming. Since we most likely have the phone plugged in, I've added a convenience yarn command to run the app (on Android) wiping the data first.
Something similar might be doable for iPhone but haven't looked into it.

[Android] Added a command to package.json to allow for a fresh run of the app

---

src/screens/PairDevices/Paired.js

Allows the pairing screen to fetch the paired name after editing.
Feature
https://ledgerhq.atlassian.net/browse/LL-1367

LL-1367 Paired screen to choose stored name if available

---

package.json
yarn.lock

There is a regression in Android that was breaking the top bar navigation inside the manager. This rendered the buttons useless (sometimes the first click worked) but had the slide navigation still work. By updating react-navigation to the latest version this seems to be solved.
Regression
https://ledgerhq.atlassian.net/browse/LL-1411
Sadly since this involves bumping the react-navigation library it can potentially affect things like text selection (throwback to that time where operation details stopped being selectable) and basically anything in the app.

LL-1411 Broken top Tab Navigation in Manager

---

src/components/DeviceJob/StepRunnerModal.js
src/components/ErrorCrossBadge.js
src/components/ErrorIcon.js
src/components/GenericErrorView.js
src/icons/USB.js
src/locales/en/common.json

I didn't add the close button because I didn't see an easy way of adding it, if it's a big deal (you can dismiss and close with the X top right) I can dedicate more time to it.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-1387
Inside the manager, when selecting a device, refuse the authorization on the device. It should trigger the above error instead of the one shown in the issue. We could potentially show a different device icon depending on the device since we can refuse on both types of devices... but I think it's good for now.

LL-1387 Changed the look of the UserRefusedAllowManager error

---

src/screens/Settings/General/CountervalueSettings.js
src/screens/Settings/General/RateProviderSettingsRow.js

Same as [LL-1388 ](https://github.com/LedgerHQ/ledger-live-desktop/pull/2010) but for mobile, it adds BTC as a valid countervalue to set up and also hides the rate provider like on Desktop.
Feature
https://ledgerhq.atlassian.net/browse/LL-1412

Ll 1412 - Mobile - Add Bitcoin in the list of possible countervalues

---

ios/ledgerlivemobile.xcodeproj/project.pbxproj

x86_64 libcore binaries needed for the iPhone simulator where embedded when doing an _archive_ to deploy on App Store, which was getting promptly rejected unless removed manually.
This should fix that ⓒ 
Bugfix
- https://ledgerhq.atlassian.net/browse/LL-916
- #263 
- Archive
- Publish
- ???
- Profit

[iOS] Strip x86 libcore binaries on "archive"

---

src/screens/Manager/AppsList.js

We (I) were incorrectly pointing to `manager.apps.noapps` instead of `manager.apps.noApps`
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-1413
- Go to manager -> Select a divice
- In app catalog search input type "skoheshw"

LL-1403 No Apps literal

---

src/screens/Manager/AppAction.js

Modal actions involving interactions with the device should not allow the modal to be dismissed (it still can be cancelled if the X is shown). However, on end cases such as a success or an error, the modal should once again become dismmissable by tapping on the backdrop/pressing back.
UX Polish
https://ledgerhq.atlassian.net/browse/LL-1410
Bottom Modals (install, uninstall, genuine check, etc)

LL-1410 Allow modal dismiss on success/error

---

src/screens/Portfolio/Header.js

fixing a small visual bug on the portfolio screen causing the distribution button to be pushed off-screen when the content block (either error or greeting title) is too large.
bug fix
LL-1525
portfolio screen header

Ll 1525 visual bug portfolio header

---

src/screens/SendFunds/SummaryRowCustom.js

Basically the right container wasn't receiving any styles, so it wasn't expanding to the fill the parent, I don't understand the need for an explicit display width use here so maybe I'm missing something.
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-1562
Summary screen, addresses should be visible without going offscreen. There should be a wrap to a second line. In the case of needing a third line it will ellipse, this was in place but could be expanded to 3 lines if we need it (?)

LL-1562 Allows Recipient/Sender to use the width of the screen properly

---

src/components/OperationRow.js

We keep the use of the account name instead of "sent/receive" but lose the currency icon.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-1552
On the portfolio history, the list rows should no longer display the currency icon but rather the transaction status indicator.

LL-1552 Show transaction status instead of asset icon in portfolio

---

src/config/urls.js
src/families/SendRowsFee.js
src/families/bitcoin/SendRowsFee.js
src/families/ethereum/EditFeeUnitEthereum.js
src/families/ethereum/EthereumFeeRow.js
src/families/ethereum/ScreenEditFee.js
src/families/ethereum/ScreenEditGasLimit.js
src/families/ethereum/SendRowGasLimit.js
src/families/ethereum/SendRowsFee.js
src/families/ripple/SendRowsFee.js
src/locales/en/common.json
src/screens/SendFunds/04-Summary.js

Adds a slider to select the gas of a transaction for Ethereum-like currencies
Feat
LL-1363
Send Flow => step 4 Summary => edit gas

slider for Ethereum transaction

---

src/components/CurrencyInput.js
src/locales/en/common.json
src/screens/Portfolio/Header.js
src/screens/SendFunds/03-Amount.js
src/screens/SendFunds/04-Summary.js
src/screens/SendFunds/AmountInput.js

In the current state of common, it only works with bitcoin family since the ethereum bridge doesn't implement a way of setting the `useAllAmount` extra (~i think this is the cause~ it was). Once https://github.com/LedgerHQ/ledger-live-common/pull/296 is merged in common and we bump it, this pr would work for eth too.
Feature
https://ledgerhq.atlassian.net/browse/LL-1392
Send flow

LL-1392  Sendmax functionality

---

src/screens/Distribution/DistributionCard.js
src/screens/Distribution/index.js

Fixed distribution flatlist item keys were not generated
Hiding distribution asset card percent and countervalue when no countervalue is available
Bug Fix
Distribution Screen

fixed distribution placeholders when no countervalue

---

src/components/ParentCurrencyIcon.js
src/screens/Account/AccountHeaderTitle.js
src/screens/Distribution/DistributionCard.js

Add double icons (parent && token) to the account header and distribution panels
Ui Polish
Distribution screen / Token Account Screen

added parent currency icons

---

src/families/ethereum/EditFeeUnitEthereum.js

fix ui glitch where having two figures in the slider fee selection screen who push and crop the "slow" and "fast" text
UI Fix
Slack Feedback
Fees Slider selection screen

fixe ui glitch on slider fees

---

src/screens/Account/index.js

Prevent switching graph to countervalue view when no countervalues are available
UX improvement
LL-1666
Account view

LL-1666: Prevent switching graph view when no countervalues

---

src/components/HelpLink.js
src/config/urls.js
src/screens/PairDevices/RenderError.js

This will change the url of the ble pairing error but also allow an override of the help link url for other uses.
Feature
https://ledgerhq.atlassian.net/browse/LL-1620
Deny ble pairing to trigger the error, check the url matches https://support.ledger.com/hc/en-us/articles/360025864773

LL-1620 Allow for error specific urls for the HelpLink component

---

src/families/ethereum/TokenNetworkFeeInfo.js
src/screens/AddAccounts/03-Accounts.js

if no existing account is found, will pre-select the last potential new account in the list.
UI Polish
LL-1673
Add account -> Scan account screen

updated pre-selecting account strategy

---

src/screens/SendFunds/03-Amount.js

XRP was showing the send max button when it can't currently handle that functionality
BugFix
https://ledgerhq.atlassian.net/browse/LL-1710
Send flow for XRP account, amount step should no longer show the send max button

LL-1710 Hide send max for currencies that can't handle it

---

src/config/urls.js
src/locales/en/common.json
src/screens/OperationDetails/Content.js
src/screens/OperationDetails/Modal.js

> :information_source: Related PR: https://github.com/LedgerHQ/ledger-live-desktop/pull/2201
This PR adds related `subOperations` to the operation detail view. It helps users understand why some transactions they may not have made are there (e.g. in the case of ETH, when sending tokens, an ETH fee will apply which shows up as a separate transaction).
<a href="https://user-images.githubusercontent.com/1671753/61643976-2eb8fc80-aca4-11e9-8e08-bd210dca7c87.png"><img src="https://user-images.githubusercontent.com/1671753/61643976-2eb8fc80-aca4-11e9-8e08-bd210dca7c87.png" height=300 /></a> <a href="https://user-images.githubusercontent.com/1671753/61643972-2eb8fc80-aca4-11e9-8e9e-6f51c5551e3c.png"><img src="https://user-images.githubusercontent.com/1671753/61643972-2eb8fc80-aca4-11e9-8e9e-6f51c …

LL-1589: See related transactions in ETH fee operations

---

android/app/src/main/res/xml/usb_device_filter.xml

It seems that the usb filtering declared in `usb_device_filter.xml` needed `vendor-id` and `product-id` to be decimal values and we had hex for the vendor. This results in the attribute being ignored and only filtering by `product-id` causing things like https://github.com/LedgerHQ/ledger-live-mobile/issues/959
BugFix
https://ledgerhq.atlassian.net/browse/LL-1714
In order to test this @Arnaud97234 there is no easy way for you to do it, but I think that the qa part should focus on verifying that the app still works for legit devices (blue, x, s) and let https://github.com/LedgerHQ/ledger-live-mobile/issues/959 verify it fixes the issue once it's merged.

LL-1714 Change vendor id to dec

---

src/screens/Accounts/AccountRow.js

rendering token list with condition at the render level was slow (especially on android) because it needed to mount / unmount each tame.
Token list is now always mounted and the toggle button hide them with style.
Bug Fix
N/A
Accounts screen -> Rows with tokens

now using style to toggle token list display

---

src/components/OperationRow.js
src/screens/OperationDetails/Content.js
src/screens/OperationDetails/index.js

Overrides the left/right buttons on operation details if we are in a suboperation allowing the user to go back to source operation without closing the whole thing.
Feature
https://ledgerhq.atlassian.net/browse/LL-1708
ected / Test plan
Operation details for an operation with suboperations

LL-1708 Allow user to go back to operation details from suboperation

---

src/components/CurrencyInput.js
src/screens/SendFunds/AmountInput.js

Currency input will now adjust the font size regarding of the available width against the number of characters in order to display the largest string possible. The font is then dynamically adjusted.
UI Polish
LL-1712
Send Screen -> Currency Input

LL-1712 adapting font size to width to display more

---

src/components/CurrencyRate.js
src/screens/Distribution/DistributionCard.js
src/screens/Distribution/RingChart.js

Fixing distribution colours and usage of lib-common's `getCurrencyColor`
Bug Fix
LL-1717
Distribution screen

fixed token colours on asset distribs

---

src/locales/en/common.json
src/screens/Account/TokenAccountsList.js
src/screens/Account/index.js

If an eth account has funds but no token, display a touchable.
If an account has 3 tokens or less , render the full list
If an account has more than 3 tokens, render a collapsable list
If an account has no funds and no token, display a generic empty state
UI Polish
N / A
Account -> Token list

added a button to expand a shortened token list

---

src/actions/accounts.js
src/locales/en/common.json
src/reducers/accounts.js
src/screens/AddAccounts/03-Accounts.js

Reuse logic of live-common for the add accounts logic that have the logic for sections, have "accounts to migrate" section and also will correctly dedup the accounts.
bug fix / feature
LL-1716
add accounts

Uses live-common logic for addAccounts

---

src/actions/settings.js
src/components/SetEnvsFromSettings.js
src/index.js
src/locales/en/common.json
src/reducers/accounts.js
src/reducers/settings.js
src/screens/Account/TokenAccountsList.js
src/screens/Account/index.js
src/screens/Accounts/AccountRow.js
src/screens/SendFunds/01-SelectAccount.js
src/screens/Settings/General/HideEmptyTokenAccountsRow.js
src/screens/Settings/General/index.js

Adds a toggle in the _General_ settings page to hide token accounts with 0 balance.
This selectively hides the accounts only in some part of the UI:
- Accounts screen
- Token list in parent account screen
- Send modal (including search)
Other parts shouldn't be affected by this toggle, like (non exhaustive list):
- Operations
- Operation details
- Receive flow
- …
HODL for now until #965 gets merged
Feature
LedgerHQ/ledger-live-common#294
LedgerHQ/ledger-live-desktop#2198
https://ledgerhq.atlassian.net/browse/LL-1477
- Accounts screen
- Token list in parent account screen
- Send modal (including search)

LL-1477 Hide empty token accounts

---

src/components/SelectableAccountsList.js
src/screens/AddAccounts/03-Accounts.js

There was a fun bug in the add account flow when we tried rendering an empty state in would sometimes cause a crash. This addresses it.
Bug Fix
Add account flow. To replicate this *before* using this fix, you can use mock and add ethereum accounts on the device, it should crash after finding the first two accounts. On this branch it should work as expected.

LL-1807 Fixes crash on empty state rendering on Add Account flow

---

src/screens/OperationDetails/Content.js

Token transactions dont use correct currency to display fees. This PR fixes that.
Bug fix
LL-1823
Operation details

LL-1823: Fees should use the parent account currency for token TX

---

src/locales/en/common.json
src/screens/Account/EmptyStateAccount.js

> :information_source: Desktop: https://github.com/LedgerHQ/ledger-live-desktop/pull/2299
This PR adds an empty state for ERC20.
UX Polish
LL-1786
Ethereum accout screen
Other account screens (check ERC20 CTA isnt displayed)

LL-1786: Add ERC20 empty state

---

src/screens/ReceiveFunds/01-SelectAccount.js
src/screens/SendFunds/01-SelectAccount.js

This PR allows searching by ticker in the account selection screen.
UX improvement
LL-1661
Account selection screens (Send / Receive funds)

LL-1661: Allow searching by ticker

---

src/locales/en/common.json

This PR includes more generic wording (i.e. don't assume it's always a Nano X)
Wording
LL-1836
Can't open device error

LL-1836: More generic wording when connection fails

---

android/app/build.gradle
android/app/src/main/java/com/ledger/live/MainApplication.java
android/settings.gradle
package.json
yarn.lock

There were apparently lingering references to the old name of the module (that's what happenes when you've never done this before) and also some references on the fork itself. I had to remove them from here and bump a new version of the fork https://github.com/LedgerHQ/react-native-touch-id
Bug Fix
Make sure you are able to build the project. I was able to build locally and test the touch id functionality.

Remove references to old module, bump fork

---

ios/ledgerlivemobile.xcodeproj/project.pbxproj

Following the work of https://github.com/LedgerHQ/ledger-live-mobile/pull/1033 this was also lingering there, pointing to the old library. Preventing the build on ios.
Bug fix

Remove reference to old react-native-touch-id for pbxproj

---

src/analytics/segment.js
src/logic/cleanBuildVersion.js
src/screens/SendFunds/ValidateOnDevice.js
src/screens/Settings/About/AppVersionRow.js

Feature
https://ledgerhq.atlassian.net/browse/LL-1848
The about section of settings should reflect a compound value for the Version on Android. iOS should remain the same. Also make sure I'm not breaking the stats :trollface:

LL-1848 Show architecture + version for android

---

package.json
yarn.lock

This allows to build on xcode preventing the error we were getting.
Should be tested on Android/iOS with a nano x to ensure the communication is still working over ble.

Bump to 1.1.0 to fix ios build

---

ios/ledgerlivemobile.xcodeproj/project.pbxproj

In the process of switching to our own fork of [react-native-touch-id](https://github.com/LedgerHQ/react-native-touch-id), we missed binary linking back the native lib in XCode project.
Curiously it seems it only broke *enabling* the biometric auth, users with the option enabled in a version prior to the regression were still able to unlock as usual.
Regression fix.
#1036
Enabling TouchID or FaceID on an iPhone should now work.
#1053 is needed for being able to build for testing

LL-1900 [iOS] fix enabling biometric auth

---

src/screens/Onboarding/steps/get-started.js

Disable the import from qr code if readonly mode is enabled and we are on the nano x option. This only applies to iOS since on Android we have no read only mode.
Feature
https://ledgerhq.atlassian.net/browse/LL-1779

LL-1779 Disable the import option when we are onboarding a nanoX from readonly mode

---

android/app/src/main/res/xml/usb_device_filter.xml
yarn.lock

This pr is supposed to fix a bug where a nano s on version 1.6 is no longer detected when plugged into an android device. This is caused by us not having the correct product id listed in the usb_device_filter.xml file. However, there is a chance that this on its own is not enough and we might need to also include the product id at the @ledgerhq/ledgerjs level.
I'm unable to test this currently but if someone can build and make sure a 1.6 nanos is detected again on Android, then it works.

Add the 1.6 product id to usb_device_filter.xml

---

src/locales/en/common.json

Live-common was already bumped enough to have have the svgs and links for crypto.com so all that was missing was this description, took longer to write this description that the one used in the app.
Feature
https://ledgerhq.atlassian.net/browse/LL-2013
Partners screen

LL-2013 Add crypto.com description for the partners page

---

src/components/InfoModal.js
src/families/tezos/DelegationFlow/SelectValidator.js

It still doesn't make any sense to me to have a text input in a drawer, but at least it's working.
Android was handling this without issue, out of the box.
Bug fix
Tezos integrations
Adding a custom validator in delegation flow

Fix keyboard covering bottom modal on iOS on select validator screen

---

src/components/SelectableAccountsList.js
src/families/tezos/DelegationFlow/SelectValidator.js
src/locales/en/common.json

- Fix wording on _Add Account_ screen, which was displaying "+N tokens" even for subaccounts.
- Prevent closing the whole delegate navigation stack from the _Selector Delegator_ screen.
UI Polish
Tezos integration
- Add accounts
- Delegate

Tezos polish

---

ios/ledgerlivemobile.xcodeproj/project.pbxproj

There were some left-over references to the analytics lib in `ledgerlivemobile` project, which should be handled by Cocoapods in `Pods`.
Surprisingly, this was working anyway for most people, but failing for others.
Build fix
RN 0.61 upgrade
Building for iOS
Make sure it didn't break analytics

[iOS] Fix build failing on some machines

---

ios/Podfile.lock
package.json
yarn.lock

Bumping libcore to get fix from LedgerHQ/lib-ledger-core-react-native-bindings#46
Bug Fix
Tezos integration
Sending funds from a tezos KT account on iOS

[iOS] Fix send from KT account

---

ios/Podfile.lock
ios/ledgerlivemobile/AppDelegate.h
ios/ledgerlivemobile/AppDelegate.m
package.json
src/context/AuthPass/auth.js
src/context/AuthPass/methods/biometry.js
yarn.lock

Due to the old library seemingly being no longer maintained, this switch might be beneficial for us. Note that we are using an older version 2.6 than the latest since in order to benefit from the 3.0.x version we'd need to upgrade to react-native 0.60+ I believe @MortalKastor is working on this so once that part is done we could bump this library too.
This might be beneficial for the issues experienced by some users when using biometric authentication. 
I'm still figuring out some kinks (coming back to the app on ios does a weird placement of the prompt behind the logo screen for instance)
Code Quality Improvement

Change from react-native-touch-id to react-native-fingerprint-scanner

---

ios/ledgerlivemobile/Info.plist
src/components/PasswordInput.js

UI Polish
Password lock screen on iOS 13, with dark mode on

[iOS] Fix invisible chars in password field when OS is in dark mode

---

android/app/build.gradle
package.json

Tiny QOL/DX PR: the app in debug mode (`yarn android`) is using the same id as the production one (`com.ledger.live`), which prevents running the former without uninstalling the later. Pretty annoying when you're on the go and testing on your personal phone.
This fixes that by adding `.debug` as a suffix to the app id when in debug, and updates `yarn android` accordingly.
QOL / DX
Trying to do Android dev during a major transportation strike.
Running `yarn android` targeting an Android phone with the production app installed should install and run the debug app without touching the production one.

[Android] Debug app doesn't replace production one

---

src/components/Graph/DefGrad.js

There was a regression in the graph chart that broke the lineargradient introduced when updating the `react-native-svg` library due to a less lenient rendering of the gradients that meant we'd show a solid color instead of the gradient. This fixes that
Regression
Slack
Graphs

Add gradientUnits to lineaGradient to fix regression

---

src/screens/Account/SubAccountsList.js

LLM UI issue on eth accounts with lot of ERC20:
an issue occured when sub account list view has too many accounts to show, thus not correctly rendering the Ui list and making it unusable for long lists of accounts.
```diff
- some UI warnings are still present related to react-navigation
```
Bug Fix
Jira
SubAccount List view

Fixed ui issue on SubAccounts List view

---

android/app/build.gradle
android/app/src/debug/java/com/ledger/live/ReactNativeFlipper.java
android/app/src/main/AndroidManifest.xml
android/app/src/main/java/com/ledger/live/MainApplication.java
android/gradle.properties
ios/Podfile
ios/Podfile.lock
ios/ledgerlivemobile.xcodeproj/project.pbxproj
ios/ledgerlivemobile/AppDelegate.m
scripts/post.sh

Integrating [Flipper](https://fbflipper.com/), to get some more debug informations.
Not as useful as I hoped for the time being, but at least we get the full network requests and responses from libcore on iOS 🎉
- Install [Flipper](https://fbflipper.com/) on your computer
- Launch it 🚀
- Run Ledger Live Mobile in debug as usual
- I found nothing interesting we didn't already have with out current tools for Android, but Flipper for RN on Android lags a bit behind its iOS counterpart, so it might get better with time
- It's currently only compatible with the simulator on iOS
Debug tool integration
https://ledgerhq.atlassian.net/browse/LL-2081
App building, so native dependencies as well
Since I had to trick a bit some XRP lib dependencies in order to prevent them to bundle an old lib over …

LL-2081 Flipper integration 🐬

---

android/app/build.gradle

Due to a crash at launch detected by @Arnaud97234 on the emulator for Android v9 we are disabling this for now.
Bug

Disable hermes

---

src/screens/ReceiveFunds/02-ConnectDevice.js

Found this while going over the support tickets, it has affected quite a few users in readonly mode and hopefully this solves the issue.
Bug fix
https://ledgerhq.atlassian.net/browse/LL-2106
Testing the app in read only mode in general but this affects the receive flow specifically. Clicking on the big Receive button in an account, crashed the app.

Fix infinite loop crash readonly iOS receive flow

---

src/screens/BenchmarkQRStream.js
src/screens/DebugWSImport.js
src/screens/ImportAccounts/Scan.js
src/screens/SendFunds/ScanRecipient.js

In the latest version of LLM, the app sometimes freezes when opening Live QR Import screen (and maybe when scanning a recipient address) on Android (probably because of one or several lib bump we did recently (React Native, React Navigation and React Native Camera specifically)).
This should fix that.
The video feedback from the camera now lags a bit behind the mounting of the screen, so it's black during the transition animation (modal slide up).
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-2107
- Live QR import
- Recipient QR address scan

LL-2107 Fix freeze when opening Live QR on Android

---

src/locales/en/common.json
src/screens/Settings/CryptoAssets/Currencies/CurrencySettings.js

When accessing the settings for a currency without any options we will now display a placeholder text according to the issue.
Feature
https://ledgerhq.atlassian.net/browse/LL-2104
Looking at XRP for example, go to `settings/crypto assets/currencies/xrp`

LL-2104 Add a placeholder text for assets without settings

---

package.json
src/screens/Distribution/index.js
src/screens/Settings/CryptoAssets/Currencies/CurrencySettings.js
yarn.lock

bump react-native-hid version
for usb communication issues on older android devices
Bug fix
LL-2112
Usb device communication on android

LL-2112 react native hid version 5.6.0 -> 5.6.2 

---

src/components/OperationRow.js
src/screens/OperationDetails/index.js

On operations details screen, back arrow is missing on sub accounts.
Bug Fix
issue LL-2125
On Operations details the back arrow shows up on operations and sub operations view and navigates back to the account details page.
On sub operations screen a close icon is shown, closing the sub operation modal screen.

ERC20 operation details: Back arrow icon is missing

---

src/locales/en/common.json
src/screens/OperationDetails/Content.js

Since the information circle triggered a modal that was aimed at erc20 tokens specifically I removed it until we have a better solution or different link/content for subaccounts. Ping @aramab 
Bug fix
https://ledgerhq.atlassian.net/browse/LL-2066
On the operation details page of an operation containing subaccount operations (think Tezos) the section that is shown above as "Subaccount operations" would read "Token operations".

LL-2066 SubAccounts header on operation details

---

package.json
src/live-common-setup.js
yarn.lock

For the test plan, Please refer to
https://github.com/LedgerHQ/lld-v2/pull/164
it will be similar but we need to test in both iOS and Android because known implementation difference we noticed in the past.

Bump live-common with latest socket implementation

---

src/components/AccountCard.js
src/components/AccountDistribution/Row.js
src/components/OperationRow.js
src/components/StepHeader.js
src/components/SubAccountRow.js
src/families/tezos/AccountBodyHeader.js
src/families/tezos/DelegationDetailsModal.js
src/screens/Account/AccountHeaderTitle.js
src/screens/AccountSettings/AccountNameRow.js
src/screens/Accounts/AccountRow.js
src/screens/Manager/DeviceNameRow.js
src/screens/SendFunds/SummaryFromSection.js

LL-2171 Trancate long account name on asset allocation screen

---

src/components/OperationRow.js
src/screens/Account/index.js

as mentioned in #1146 
we should prevent double click navigation pushs
best solution yet is to debounce them.
Bug Fix
LL-1888
Accounts tokens links and sub operations aswell

 LL-1888 debounce clicks on navigations push

---

src/screens/SendFunds/02-SelectRecipient.js

Fix enabled Continue button when address is empty

---

src/live-common-setup.js

ERC20 tokens went missing from the whole app, this restore them.
Bugfix

Fix ERC20 not showing up anymore

---

src/components/Delta.js

Issue on graphs delta in zero case where the arrow up was showing
now theres no arrow in this case
**to confirm with design**
UI Polish
Graphs delta values
Select an account or period with a variation delta of zero to see this

(Delta): arrow doesn't show on zero delta cases

---

package.json
yarn.lock

bump live-common  version 12.1.0
to be check all is good. we can focus the test on adding and sending one BTC tx. and also test one ERC20 for instance, and tezos. that should be enough coverage.

bump live-common 12.1.0

---

src/families/tron/AccountBalanceSummaryFooter.js

https://ledgerhq.atlassian.net/browse/LL-2340
Account Bandwidth was incorrect:
Before:
Now:
Bug fix
TRX account with frozen amount.

LL-2340 : fix formattedBandwith calculation on TRX Account screen

---

package.json
yarn.lock

Bump live-common version to [12.9.0](https://github.com/LedgerHQ/ledger-live-common/releases/tag/v12.9.0)
- :deciduous_tree: send max + operation number of confirmation fixes
- some special eth accounts fixed (no need to confirm that, but confirm that all is fine for ETH can be good, our tests confirm it anyway and it only impact the sync)

bump live-common version to 12.9.0

---

src/context/LedgerStore.js
src/reducers/settings.js
src/screens/Settings/General/CountervalueSettings.js

This pr introduces the automatic fallback to using USD as a counter value when the currently selected counter value is not reported as supported. Without this, users who have selected a non-supported fiat counter value will see their total balances and graphs as broken.
Feature
Slack conversation, no Jira task as far as I know
Parts of the app affected / Test plan
- With the **desktop** application stopped and before this https://github.com/LedgerHQ/ledger-live-desktop/pull/2795 gets merged
- Edit your `app.json` and set the counter value to something not supported (but contemplated in https://github.com/LedgerHQ/ledger-live-common/blob/1a29a3bc5f533ee29e0a47c577a1a7e068546e0b/src/data/fiat.js#L23-L73. 
- Launch the app, open the console, and export the accounts/settings. You'll see a …

Fallback to USD when the user selected fiat counterValue is not supported

---

fastlane/Fastfile
package.json

Make release easier from our devs machine (the other workflow was made for Jenkins CI)
Improvement
LL-2372
CI
In this PR I've added a few scripts to make it easier to release from our own local computers.
- `yarn beta`: is almost like `yarn internal` but with lesser checks so easier to run local. this script _should_ release both iOS and Android (starting with iOS)
- `yarn ios:upload` and `yarn android:upload`: make it easier to just start an upload (does not recomple the apps, will just start the upload process)

new scripts to make it easier to release from local machines

---

src/screens/Settings/Accounts/BlacklistTokenModal.js

This pr resets the state of the blacklist modal every time it's closed, before it will only show the first step the first time.

Fix to reset modal confirmation for blacklisting tokens

---

src/families/tron/AccountBalanceSummaryFooter.js
src/screens/Account/index.js

(TRX): account header rounding removed from graph title and added to spendable balance
UI Polish
Go to a trx account with a decimal balance.

(TRX): spendable balance rounding update

---

src/screens/FreezeFunds/04-ValidationSuccess.js

Fixed navigation issue after freeze success to vote then close after vote success
###Type
Bug Fix
Freeze tron assets 
wait 60 seconds
Vote
Go till the end of the voting process
on the success vote page when clicking on close you should be redirected to the accounts page

(TRX): fix navigation issue after freeze success

---

src/components/ProgressCircle.js

Issue on votes used flooring
UI Polish
LL-2378
Use almost all of your TRX votes
You will then see the banner telling you you used 99% of your votes at maximum

LL-2378 (TRX): percentage votes used flooring fixed

---

src/components/DBSave.js
src/context/LedgerStore.js
src/context/Reboot.js
src/db.js
src/index.js
src/screens/Accounts/AccountOrder.js
src/screens/Settings/Debug/GenerateMockAccounts.js
src/user.js

(DB): updated accounts storage saving process to split the data by account key and not grouped
SQLite accounts data is now stored by account keys thus removing certain limitation of storage we can have on android
Bug Fix
LL-2295
**Surface:** on iOS and Android, everything related to the app data is touched. Especially and mainly the accounts data that have been optimized and that fixes a limit getting reach when you have high number of accounts loaded.
**Compatibility:** coming from an old app version TO this PR version should properly migrate your accounts in a way that it is totally smoothless for you to see this happening. **However** moving back to old version (of develop) is NOT supported and you need to reset your app, something that can never be done on store as we never go …

LL-2295 Android: fixes app to freeze at boot due to SQLite limit reached (2 MB) – change our db to store per account

---

src/families/tron/VotingFlow/02-VoteModal.js

Focus input on vote edition modal on step 2 of the voting flow.
The autofocus was not reliable so moving to a more imperative approach using modalShow event.
UI Polish
LL-2376
Tron voting flow step 2 on edition of votes modal.

LL-2376 (Tron): vote modal focus input on modal open

---

src/screens/Account/AccountActions.js

(Tron): fix issue on tron accounts action buttons having scroll on read-only mode when its not necessary
Ui Fix
Tron accounts page actions when using read-only mode

(Tron): fix account actions read-only mode issue

---

src/screens/SendFunds/04-Summary.js

Same as https://github.com/LedgerHQ/ledger-live-desktop/pull/2949 but for mobile, I'm moving the Jira task back to dev review since it was grouped for both.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-2590
Sending a token, make sure that we dont show the total to debit if the amount and the total are the same.

Hide the total section on the send flow when it equals the amount

---

src/components/DelegationDrawer.js
src/components/ModalBottomAction.js
src/components/RequireTerms.js
src/families/tezos/DelegationDetailsModal.js
src/modals/Create.js
src/screens/Accounts/AccountOrderModal.js

Removal of potentially lagging and unnecessary SafeAreaViews from the bottom modals causing glitches.
To reproduce the glitch before you could try and refresh the portfolio and immediately opening the transfer modal in the bottom tab bar to see that an unnecessary padding was added then removed with a lag.
Any throttling of the app would trigger that.
Bug Fix
LL-2459
The modals updated are:
- Transfer on the bottom tab menu
- Require and read terms
- Every modal action ( delete an account)
- the sort accounts modal
- Delegation details modal for tezos and cosmos

LL-2459 Modals glitch issue

---

src/components/RootNavigator/ExchangeNavigator.js
src/screens/Exchange/Buy.js

Buy crypto screen:
- tab title label should not be in uppercase anymore
- tab title should be semi bold when tab active
- "Buy crypto via our partners" should be semi bold
UI Polish
LL-2686
Open the buy crypto page

LL-2686 (BuyCrypto): minor style polishes

---

src/locales/en/common.json

We were missing the NotEnoughGas translation in our files, thus resulting in a strangely generic error wirth "NotEnoughGas" as title error.
We fix this mistake right here, right now
Error Fix
https://ledgerhq.atlassian.net/browse/LL-2649

add text and title to NotEnoughGas error

---

src/components/RootNavigator/CryptoAssetsSettingsNavigator.js
src/components/RootNavigator/ExchangeNavigator.js
src/components/RootNavigator/MainNavigator.js

UI Polish
https://ledgerhq.atlassian.net/browse/LL-2837
Check that the active state of the bottom navigation tabs uses the correct color.
Also for the Buy crypto  and Settings/crypto assets screens the bottom indicator underline should use the correct blue now.

LL-2837 Use #6490f1 for active tab icon/text color

---

src/components/DeviceJob/StepRenders.js

Added some padding for the error bottom modal for devicejobs and increased the margin to follow the design guidelines, the descriptions should stop narrower than the button, we tend to forget this.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-2695
Try to access a device and force a disconnect on the manager, or any other flow that tries to connect to the device. On the screenshots there are two of the options, but there are more cases, all should look good and not like on the linked issue.

LL-2695 Fix styling for devicejob error bottom modals

---

src/components/RootNavigator/ExchangeBuyFlowNavigator.js
src/screens/Exchange/Buy.js
src/screens/Exchange/History.js
src/screens/Exchange/SelectAccount.js

Following up on a conversation with design and Chris (who doesnt seem to have a github account) we agreed that the steps are dropped so we don't use the step title. Just good old centering.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-2692
https://ledgerhq.atlassian.net/browse/LL-2691
Test that the header titles of the buy crypto flow are centered and that the empty placeholder is. using a bold text.

LL-2691 Center headers on buy crypto flow

---

src/screens/Asset/index.js

In Asset allocation screen the balance countervalues were not centered
UI Polish
LL-2708
Go to the asset allocation then long press on a currency to go to the correct page.

LL-2708 (AssetAllocation): fix balance centered

---

src/locales/en/common.json
src/screens/Manager/Device/index.js

(Manager): deprecated firmware banner with support contact link added
HODL: needs a live-common bump
Feature
LL-2645
Manager

LL-2645 Deprecated firmware banner

---

src/locales/en/common.json
src/screens/Distribution/index.js

Bug Fix
https://ledgerhq.atlassian.net/browse/LL-2972
Asset allocation screen
- Be a maximalist
- Check there is no "s" on your one and only asset

LL-2972 Add singular to Asset allocation screen

---

android/app/src/main/AndroidManifest.xml

To be tested whether this breaks the activity flow of things like the biometric scans, app locks, etc since they send the activity to the background and perhaps this setting could mess with that. Initial testing shows the app still launches and no obvious crash, so leaving this for qa @nabil-brn @Arnaud97234

Addresses strandhogg v1/v2 vuln

---

src/families/cosmos/Delegations/LabelRight.js
src/families/cosmos/Delegations/index.js
src/locales/en/common.json

Delegation flow is locked from the start with some info when user can delegate more with an account.
Bug Fix
LL-2883
Cosmos accounts with less than 0.16 ATOM to be able to start delegating

LL-2883 (Cosmos): Add delegation disabled when not enough balance

---

src/screens/Portfolio/index.js

When the portfolio screen is showing a placeholder (+banner, or on small screens that make it scrollable) disable the sticky header that shows the total balance since it makes no sense.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-2778
With a small screen device, or forcing the "buy banner" to appear, on an empty state app (no accounts or no movements), scroll down until the sticky header would be showing. Make sure it doesn't show. If it shows, this pr is invalid and should not pass qa.

LL-2778 Hide portfolio's sticky header if placeholder

---

package.json
yarn.lock

Upgrade react native bindings 4.15.9
should fix algo sync issues when no network.

bump react native bindings 4.15.9

---

fastlane/Fastfile

remove erroneous use of `yarn version --prerelease` in the `yarn internal` script

fix fastlane scripts

---

src/screens/Account/AccountHeaderTitle.js

Account header title ellipsis issue on long account names
UI Polish
LL-3096
Open any account and rename it with a very long name.
The header title should no longer overlap with the settings icon in the header.

LL-3096 (Account): account header title ellipsis issue fixed

---

package.json
src/screens/FirmwareUpdate/02-CheckId.js
yarn.lock

LL-3066
split FW hash to be displayed the same way nano S|X display them
We do not have the firmware update implemented on mobile yet, but as a safe guard, updating the component so it doesn't break
https://github.com/LedgerHQ/ledger-live-common/pull/842 waiting for it to be merged and live-common bumped

add new format to firmware hash

---

src/families/cosmos/AccountBalanceSummaryFooter.js

(Cosmos): account balance footer remove unecessary info when balances at zero
UI Polish
Ll-2877
Cosmos accounts with no delegation or no undelegations

LL-2877 Cosmos polish

---

src/components/AccountDistribution/Row.js
src/components/RootNavigator/BaseNavigator.js

Navigation back on an account page when coming from asset distribution should now go back to the previous page and not the accounts list page.
UI Polish
LL-1927
Account page navigation when coming from asset distribution flow.

LL-1927 (AccountDistribution): navigation issue fixed

---

src/families/ethereum/EthereumFeeRow.js
src/families/ethereum/ScreenEditFee.js
src/locales/en/common.json

(ETH): summary gas price and max fees updated with correct values
UI Polish
LL-3100
Do an ethereum transaction and check the summary part.

LL-3100 (ETH): summary gas price and max fees updated

---

ios/Podfile.lock
package.json
yarn.lock

contains work of https://github.com/LedgerHQ/lib-ledger-core-react-native-bindings/pull/72
the plan is to confirm there is no feature regression of this on iOS, basically on some libcore stuff (sending a btc account for instance)
the way we will then proceed is send to testflight for further testing.

Fixes iOS crashes (optimistically)

---

src/locales/en/common.json
src/screens/SendFunds/04-Summary.js

Provide a way to go to Buy whenever parent ETH account does not have enough funds to pay for the fees of the ERC20 transaction
Feat
LL-2684
Send Summary

add error and CTA to buy ETH when NotEnoughGas

---

src/logic/accountModel.js

LL-3387 (Storage): increase operation retention storage from 100 -> 500
Improvement
LL-3387
Accounts with more than 100 operations should now be stored on the client with a max of 500 operations

LL-3387 (Storage): increase operation retention storage from 100 -> 500

---

src/reducers/accounts.js

We were not making use of the helper from live-common, resulting in a partial clear cache since subAccounts were not affected. The linked Jira tasks says erc20 were being flushed but I don't see how that's possible. As a side note, on a few occasions I had to clear cache **twice** in order to see this "No operations" screen, but this can't be related to this bug, and is perhaps a good thing to take a look into as a separate bug.
Bug fix
https://ledgerhq.atlassian.net/browse/LL-3116
- Import Tron, Algorand, and Ethereum accounts with subAccounts
- Turn OFF network connection
- Clear the application cache
- Go to Portfolio page

LL-3116 Use the 'clearAccount' helper for CLEAN_CACHE

---

src/screens/Swap/Form/SelectAccount/01-SelectCrypto.js

In the swap flow, allow the user to select a currency / account pair for the destination of a swap before the source pair. This selection should no longer be cleared when selecting the source.
Bug fix
https://ledgerhq.atlassian.net/browse/LL-3568
- Go into the swap flow
- Select a destination account from for example BTC
- Select a source account from BTC too (this should be possible, but not the other way around)
- The destination should be cleared.
- Go into the swap flow
- Select a source account from for example BTC
- Try to select a destination account from BTC, this should not be possible.
- Select a destination account from for example BTC
- Select a source account from ETH.
- The destination should still be the selected BTC account.

LL-3568 Swap - Allow the destination account to be selected before the source

---

src/components/OperationRow.js

(Portfolio): OperationRow balance should not shrink and ellipsis anymore
UI Polish
LL-3463
Portfolio page and operation rows with big account names and balance digits

LL-3463 (Portfolio): operation row balance no longer ellipsis

---

src/components/ValidateOnDeviceDataRow.js

Allow the value (right element) on a `DataRow` from the validation step of the send flow and any other flow that uses it to grow while possible and then wrap to the next line as a whole instead of wrapping the ticker first. On the extreme case of the amount itself being wider than the whole scree, then it will wrap the text because there's nothing we can do about it. But at that point you're viewing the app on a watch screen.
UI Polish
https://ledgerhq.atlassian.net/browse/LL-3366
- Go through a send flow with many decimals / small screen
- Reach the device validation step
- Check that it doesn't do the OMG bug (ticker wrap) uglyness from the ticket linked

LL-3366 Wrap the value on the confirmation screen if needed

---

src/components/CurrencyRow.js

(AddAccounts): token blockchain indicator added
UI Polish
LL-3197
Add accounts currency selector

LL-3197 (AddAccounts): token blockchain indicator added

---

android/build.gradle

force kotlin version to a higher version to ensure @segment/analytics-react-native builds
(version set is 1.4.10 as it is the latest)
solution found [here](https://github.com/segmentio/analytics-react-native/issues/225)
Bug fix
Try yarn android without this should fail on build of task :segment_analytics-react-native:compileDebugKotlin
This should fix it

Fix yarn run-android due to @segment analytics build issue

---

src/screens/Swap/OperationDetails.js

Bug fix
Crash reported on slack
Make a swap from an erc20 token and try to see its op details, currently it should normally crash the app 🤦‍♀️ after this fix it should work as usual.

Blind fix for swap op details erc20 crash

---

src/locales/en/common.json
src/screens/Settings/HelpButton.js

The UI differs from the figma linked because this concept of bottom modal choice is also user for the transfer actions and the onboarding steps, I don't think it makes sense to remove the blue circles only for this one, specially with what's going to come in the future months. 
Feature
https://ledgerhq.atlassian.net/browse/LL-3538
- Go to settings,
- Click on the `?` on the top bar
- Check the link for ledger status exists and works

LL-3538 Add ledger status link to support modal

---

src/families/tron/VoteFlow/02-VoteCast.js
src/screens/FreezeFunds/02-Amount.js
src/screens/SendFunds/02-SelectRecipient.js
src/screens/SendFunds/03-Amount.js
src/screens/UnfreezeFunds/01-Amount.js

(GenericErrorModal): closing on network-down event should function now
Bug fix
LL-3113
Error modals that can be triggered from network down on send flow etc. upon clicking on cancel and close button the modal should close properly now

LL-3113 (GenericErrorModal): closing on network-down event should function now

---

src/components/SelectDevice/index.js
src/screens/Onboarding/steps/pair-new.js

During onboarding on bluetooth if device already paired we should not see the device connection modal anymore and be redirected to next step directly.
UI polish
LL-3530
Onboarding using bluetooth. check also usb if everything is ok.

LL-3530 Onboarding ConnectDevice already paired loading issue

---

src/components/Carousel/index.js

It updates the carousel nonce so that the banner shows again for those that deactivated it in the past
fix
@cthepot-ledger @Arnaud97234

update carousel nonce

---

src/components/RootNavigator/MainNavigator.js

When the user navigates to a secondary/deeper screen from the bottom tab navigator and then navigates to another tab, reset the first tab to the initial screen so that when we come back it's not still in the secondary screen. Was that clear enough? I don't think so, I'll explain better in the test plan.
Feature
https://ledgerhq.atlassian.net/browse/LL-3679
- Press the settings tab
- Click on General
- Click on the Accounts tab
- Click on the Settings tab.
We should now be on the main settings screen and **not** in the _General_ one. The same thing applies to the Accounts navigator, you should be able to access a particular account screen, go to the portfolio, come back to the accounts tab and be on the main screen and not the nested one.

LL-3679 Make settings/accounts navigators go to first screen on blur

---

src/screens/Portfolio/index.js

The carousel brought yet another regression, we lost the sticky header. But fear not, I stumbled upon this by pure chance, and brought it back. If you were wondering where the sticky header was, it's here. It's back.
Bug Fix
Slack messages
- Launch the app
- Scroll down a bit
- It is expected that a sticky header with your total balance should be visible

Bring back the sticky header on portfolio

---

src/components/CurrencyDownStatusAlert.js
src/config/urls.js
src/locales/en/common.json

rollback temporary banner measure
upon internal request, we will resume BCH services and no longer need the banner.
not sure if testable but if you have BCH no warning will appear.

remove BCH warnings

---

src/components/AccountGraphCard.js
src/components/AssetGraphCard.js
src/components/CurrencyUnitValue.js
src/components/Delta.js
src/components/GraphCard.js
src/screens/Account/ListHeaderComponent.js
src/screens/Asset/index.js

Graph balance font size and wrap issue
UI Polish
LL-3906
Balance graphs on
- Portfolio
- Account page
- Assets distribution page

LL-3906 Graph balance font issue

---

src/locales/en/common.json
src/screens/Accounts/AccountRow.js

Account row balance was cropped if too long. it now should be fixed 
UI Polish
LL-3905
Account row

LL-3905 Account row balance ui issue

---

src/screens/Manager/Manager.js

Pass the device model id and version the access manager app list event like we do on desktop
Feature
https://ledgerhq.atlassian.net/browse/LL-3875

LL-3875 Track device model id and version on enter manager flow

---

src/screens/Distribution/DistributionCard.js

Asset allocation long balance issue everything should wrap on the next line if numbers are too long
UI Polish
LL-3906
Asset allocation page

LL-3906 Asset allocation long balance issue

---

src/analytics/HookAnalytics.js
src/analytics/segment.js
src/components/AnalyticsConsole.js
src/components/RootNavigator/MainNavigator.js
src/index.js
src/screens/Onboarding/steps/welcome.js
src/screens/Settings/Debug/AnalyticsConsoleRow.js
src/screens/Settings/Debug/index.js
src/screens/Settings/PoweredByLedger.js
src/screens/Settings/index.js

> Since this includes the same bumps and updates from https://github.com/LedgerHQ/ledger-live-mobile/pull/1468 I'm HODL'ing it until we can rebase it to not include all these changes.
This pr backports the analytics console concept from LLD to LLM, allowing us to view as an overlay on the screen the events that are getting tracked via analytics. This is specially useful for product to find the name of an event to polish metrics and to identify missing or incorrect events.
It has already helped identify the fact that **we were missing all the events from the first launch of the app**. The component in charge of this was not getting the update of the `hasCompletedOnboarding` flag having changed and therefore we remained with uninitialised analytics for the duration of the first launch. …

AnalyticsConsole, debugging tool for tracked events

---

ios/Podfile.lock
src/components/DeviceActionModal.js
src/components/RootNavigator/MainNavigator.js
src/screens/Manager/AppsList/AppUpdateAll.js
src/screens/Manager/AppsScreen.js
src/screens/Manager/Manager.js
src/screens/Manager/index.js
src/screens/Swap/Form/SelectAccount/BadSelectionModal.js
src/screens/Swap/MissingOrOutdatedSwapApp.js
yarn.lock

When following an error flow end from the swap (will likely need to be integrated on Sell cc @IAmMorrow) there is a possibility that the user can have a missing exchange app, an outdated exchange app, or any number of missing/outdated currency apps. In those cases, we will prompt the user to go to the manager and install or update the app accordingly.
The first iteration of this merely redirected the user to the manager but was further improved by the work of @LFBarreto introducing the `searchQuery` concept that we could pass as a route param to the navigator and have the screen pre-filled to that currency's name. This was great, but being the nonconformist beings we are we decided it would be nicer to preselect the installed tab and show the banner to update, if that was the action the …

LL-3609 Better flow when accessing manager from Swap with query/tab

---

src/locales/en/common.json
src/screens/Lending/Dashboard/InfoModalBottom.js
src/screens/Lending/Dashboard/Rates.js

Add an info drawer when a token account is non existant in the lending dashboard
Polish
https://ledgerhq.atlassian.net/browse/LL-3877
You need to test with an eth account without having token accounts. and test after with one eth account which has token accounts.

LL-3877 add buy/receive info drawer on lending dashboard

---

android/app/src/main/AndroidManifest.xml
src/components/RequiresBLE/RequiresLocationOnAndroid.android.js

Android 10 deprecated using `ACCESS_COARSE_LOCATION` for scanning for BLE devices, and now requires `ACCESS_FINE_LOCATION` (cf https://developer.android.com/about/versions/10/privacy/changes#location-telephony-bluetooth-wifi), this broke the location permission flow when we changed our `targetSdkVersion` to `29`.
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-3990
#1476
Pairing on a _newly_ installed app.
Maybe affects only Android 10+, not sure.
- Be on Android 10 or 11
- Re-install the app (erasing data or changing the permissions in the app detail is probably not enough)
- The pairing flow should ask for location permission, and continue smoothly once allowed
I tested on my side with a Google Pixel 3 on Android 11

LL-3990 Fix location permission on Android

---

src/navigation/utils.js

There's a if/else block where we try to determine the type of view that we are trying to scroll to top, due to the fact that we wrapped the content of the portfolio screen inside a flat list and that is wrapped inside a wrapped component, the scroll to top wasn't contemplated. This adds support for _that_
https://github.com/juan-cortes/ledger-live-mobile/blob/1124a0a826f794cd159f324cd4602fa442165de2/src/navigation/utils.js#L24-L45
Bug Fix
Slack
- Open the app
- Scroll down on the portfolio screen
- Double tap on the tab
- It is expected that the screen will scroll to top

Bring back the scroll to top on bottom tab navigation double tap

---

src/components/DeviceItemSummary.js
src/components/SelectDevice/index.js
src/locales/en/common.json
src/screens/PairDevices/Paired.js
src/screens/PairDevices/index.js

A recently discovered bug was preventing the `autoSelectOnAdd` functionality from working, presumably in the whole app. The pairing flow will eventually return just the device id instead of the expected `Device` and in doing so would fail any subsequent device action linked to the particular screen. This meant that the manager flow, ~the onboarding flow~, and the swap flows would fail to connect to a newly paired device. 
This isn't a dead end, since the user can close the bottom modal, and select the newly paired device. Which would then connect without issues. But it does align with many of the connectivity issues we've been reporting/experiencing lately. Basically, if you pair a new device on the current develop it will give you an error when trying to connect, until you dismiss the …

Fix bug on autoSelectOnAdd manager pairing

---

fastlane/Fastfile

Just a small fix to make sure the remote is `upstream` when pushing git tags in android workflow

pass correct remote when pushing android tags

---

src/components/AccountGraphCard.js
src/components/AssetGraphCard.js
src/screens/Account/ListHeaderComponent.js
src/screens/Asset/index.js

The is a small _issue_, dont really know what to call it since the specs for inner bound rendering on css are so hard to understand, that makes the presence of a monospace unicode lowercase t in the ticker for bitcoin testnet, slightly displace the rest of the ticker enough to make it cut-off the top.
Removing the hardcoded line-height here fixes the issue and doesn't seem to cause any obvious UI regression.
This pr also hides the countervalue for currencies that dont have a countervalue (ie tBTC) in the account screen but also in the asset distribution screen.
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-4388

LL-4388 Styling fix for iOS monospace unicode on 𝚝BTC

---

src/reducers/settings.js
src/screens/Portfolio/index.js
src/screens/Settings/Experimental/ExperimentalHeader.js

(ImportDesktopSettings): dev mode by default issue
It should also fix IOS header overlapping issue to be confirmed
Bug Fix
LL-4578
After importing accounts from desktop with settings, the dev mode should not be set on by default anymore

LL-4578 (ImportDesktopSettings): dev mode by default issue

---

ios/ledgerlivemobile/AppDelegate.m

This pr addresses two separate issues. First, we deleted the code that was blurrying the content and adding a logo when in the app switcher mode on iOS devices. This was done as part of https://github.com/LedgerHQ/ledger-live-mobile/commit/694f503a9e94290fae31fb9d1683399ef9f8587e and essentially kills that functionality completely. Keep in mind we killed the auto-lock feature so locking only happens when you access for the first time (?)
Before merging this pr I would like the dev that dropped those lines to explain the reasoning for dropping them, since we might have done that to avoid a bug and could be introducing it again. I couldn't find anything in our jira/slack about this. It seems to work well enough.
~Second issue addresses the _`I can’t enable FaceID on 2.20`_  comment by …

LL-4450 Bring back blur on app switcher iOS

---

src/components/Button.js
src/families/tezos/DelegationFlow/Summary.js
src/screens/SendFunds/02-SelectRecipient.js
src/screens/SendFunds/04-Summary.js

(Button): rewrite in function style + cleanup of loader animation + loader can now be driven by props like a previous version supposedly
https://user-images.githubusercontent.com/11752937/106003506-8cf14780-60b2-11eb-8978-f89fed12c31d.mp4
UI Polish
LL-4378
Send flow buttons should now show a loader while bridge pending
+ Tezos delegation summary

LL-4378 (Button): fix loader animation on send flow

---

android/app/src/main/AndroidManifest.xml
ios/Podfile.lock
package.json
src/screens/DebugLogs.js
yarn.lock

When investigating the cause of the LL-1944 sharing bug on iOS I accidentally uncovered that the export for **Android** of swap history is currently not working at all. We will get prompt with a failed to share toast message due to having an outdated library and most importantly a missing permission. This sharing intent of a base64 generated file on the fly requires the external storage permission as described in https://react-native-share.github.io/react-native-share/docs/install and we simply didn't have that.
This means **current develop version has a broken swap history export**
Bug fix
https://ledgerhq.atlassian.net/browse/LL-1944
- Try exporting logs for both iOS and Android from the debug screen, it is expected that a file is generated with the data.
- Try exporting the swap …

LL-1944 Fix iOS/Android sharing in general

---

src/components/FilteredSearchBar.js

Once we start filtering on mobile on a select currency screen, we lose the marketcap sorting, this was due to a missing `shouldSort: false` option passed to `Fuse` which defaults to alphabetical sorting when not true.
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-4771
- Go to an add account flow
- Input "bit" as a search query
- Make sure Bitcoin is on top of the chain, not lower

LL-4771 Fix sorting for currency selector

---

src/index.js
src/rootnavigation.js
src/screens/WalletConnect/Provider.js

(WalletConnect): fix potential crash issue regarding navigation not init
Bug fix
LL-4604
mainly wallet connect could trigger a crash at launch, verify that it never happens and the functionality stays the same
tp reproduce the initial bug start a wallet connect session quit the app without closing the session then go back into it using wallet connect

LL-4604 navigation crash issue

---

src/screens/Account/AccountActions.js

fixes https://ledgerhq.atlassian.net/browse/LL-4696
Bug Fix
AccountActions are displayed as a BottomModal list of choices, that redirects to different flows / screens.
Since BottomModal is animated, it is finally hidden after the screen is display.
For some reason, if the next screen uses a keyboard (autofocus), the BottomModal animation end leads to Keyboard being dismissed. This can have other unwanted bugs.
To avoid any conflict, this AccountActions components retains the next screen to go to, and waits for the Modal to be hidden before transitioning to next screen.
This leads to a slight delay, but avoids conflicts.
For Polkadot (and others having additional actions):
* tap on the more button
* tap on bond
* the bottom modal closes
* the bond flow starts
**I did not test on Android …

fix(AccountActions): wait BottomModal hide before navigate to avoid kb blur - LL-4696

---

src/components/BottomModal.js

(Modals): block opening two modals at same time
Bug fix
LL-4520
Tap quick on two modal buttons per instance in the accounts page header buttons or the transfer button at the same time.
It should no longer open both modals.

LL-4520 (Modals): block opening two modals at same time

---

src/components/AccountCard.js
src/components/SelectableAccountsList.js

(AddAccount): fix add account card with tokens issue
UI polish
[LL-4960]
Add accounts flow on the select account step with tokens
[LL-4960]: https://ledgerhq.atlassian.net/browse/LL-4960

LL-4960 (AddAccount): fix add account card with tokens issue

---

src/screens/Onboarding/steps/finish.js

(Onboarding): finish replace instead of navigate to prevent back navigation at the end of onboarding flow
Bug fix
[LL-5120] [LL-5129]
Onboarding end -> portfolio -> back navigation should close app now as intended
[LL-5120]: https://ledgerhq.atlassian.net/browse/LL-5120
[LL-5129]: https://ledgerhq.atlassian.net/browse/LL-5129

LL-5120 LL-5129 fix Onboarding end navigation issue

---

src/components/DoubleCountervalue.js
src/locales/en/common.json
src/screens/OperationDetails/Content.js

(OperationDetails): add double countervalues
show countervalues at tx date and today in a tooltip in operation details modal
Feature
[LL-4353]
OperationDetails > countervalues > tooltip opens a modal with both countervalues
[LL-4353]: https://ledgerhq.atlassian.net/browse/LL-4353

LL-4353 (OperationDetails): add double countervalues

---

src/components/RootNavigator/AddAccountsNavigator.js
src/locales/en/common.json
src/screens/AddAccounts/02-SelectDevice.js
src/screens/AddAccounts/03-Accounts.js
src/screens/Swap/Form/SelectAccount/NoAccountsEmptyState.js

When doing a swap, if we select a destination currency where we dont have any added accounts **yet**, the current flow will lead the user to the `add accounts` flow and leave the swap one. This is a regression, the `add accounts` flow used to be launched inline and go back to swap after completion.
This brings that behaviour back and changes the CTA of the import to "go back to swap.
**Note** There's a discrepancy with what's listed in the Jira ticket. In the specs we reach the success step, but on the implementation we leave the accounts flow after the import step. So one step less, and we are back on Swap, like before.
Bug Fix + changes
https://ledgerhq.atlassian.net/browse/LL-5147
- Test the account selection flow on swap as described above
- Test the add account flow to make sure this …

LL-5147 Go back to swap after add accounts

---

src/families/polkadot/BondFlow/01-Started.js
src/screens/FreezeFunds/01-Info.js

UI BugFix
In EarnRewards modals (on TRON or POLKADOT), bullet list items are cropped if screen is small (e.g. iPhone SE).
Fix allows for bullet list items to go on multiple lines.

LL-3067 - fix: allow EarnRewards multiline bullet list item for TRX / DOT

---

src/screens/Portfolio/Header.js

(NotificationCenter): show status incident notif in portfolio
UI Polish
[LL-5256]
Portfolio page should show a warning icon next to notification bell if a status incident is ongoing
[LL-5256]: https://ledgerhq.atlassian.net/browse/LL-5256

LL-5256 (NotificationCenter): show status incident notif in portfolio

---

src/components/Button.js
src/context/AuthPass/AuthScreen.js

(AuthPass): fix some issue with navigation hooks imported outside of navigation context
Bug Fix
[LL-5914]
Password lock screen should no longer crash
[LL-5914]: https://ledgerhq.atlassian.net/browse/LL-5914

LL-5914 (AuthPass): fix some issue with navigation hooks imported outside of navigation context

---

src/components/AccountCard.js

(AccountCard): fix name + tag overlap issue
UI Polish
[LL-5171]
Account card  on add flow with long name should no longer overlap on chain type tag 
[LL-5171]: https://ledgerhq.atlassian.net/browse/LL-5171

LL-5171 (AccountCard): fix name + tag overlap issue

---

src/screens/Swap/FormOrHistory/Form/Summary/SummaryBody.js

> This pr is tightly linked to LedgerHQ/ledger-live-common#1244 and they should land on production together. Delivering one of them independently from the other will make the amounts not match for the users doing swaps.
Feature
Originally when we delivered the floating rate trading method for swap there was a new concept of payoutNetworkFees, which represents an amount that is charged as a fee on top of the rate provided. We needed to display this because the amount on the device included that amount, but the amount to be received had it deducted.
With the latest code on staging, this is no longer the case and the binary payload amount (which we use on the device verification) deducts this amount, allowing us to drop the UI that referred to this concept altogether.
DEPENDS ON LIVE-COMMON: …

fix(Swap): drop the concept of payoutNetworkFees from UI - LL-5931

---

src/locales/en/common.json
src/screens/Swap/FormOrHistory/Confirmation.js
src/screens/Swap/FormOrHistory/Form/PendingOperation.js

UI Polish
This PR updates the Swap Confirmation screen to show better that broadcast is successful but operation is still pending.
Icon updated with Clock, wording updated, and Swap ID filled in the Disclaimer alert.
JIRA: [LL-5733](https://ledgerhq.atlassian.net/browse/LL-5733)
At the end of a Successful Swap, should look like this:
**NOTE: Not tested with a REAL SWAP (i wanted to avoid burning fees since QA should test it for real).**
The part that i have not tested is if the targetCurrency is correctly filled in the description text.

feat(Swap): update success screen wording and UI - LL-5733

---

src/modals/Create.js
src/reducers/accounts.js
src/screens/Account/hooks/useActions.js
src/screens/Lending/shared/useCompoundAccountEnabled.js
src/screens/Swap/FormOrHistory/Form/Summary/SummaryBody.js

(Compound): disable lending entries for live with non enabled accounts
Feature
[LL-5446]
Compound entry points for accounts should be limited to accounts that have it already enabled.
Also the global entry is shown to apps having at least one lending enabled account.
[LL-5446]: https://ledgerhq.atlassian.net/browse/LL-5446

LL-5446 (Compound): disable lending entries for live with non enabled accounts

---

src/screens/NotificationCenter/NewsRow.js

As all notifications aren't designed to embed a link, array dependencies from openUrl function triggered an error.
Bug Fix
~~[Slack message](https://ledger.slack.com/archives/C01S86NNMR7/p1626445268155400) (awaiting real bug ticket)~~
[LL-6430]
Click on the notification icon when the backend is sending new notification without any link inside.
[LL-6430]: https://ledgerhq.atlassian.net/browse/LL-6430

LL-6430 App is crashing when user try to open new notifications

---

src/families/ethereum/EditFeeUnitEthereum.js
src/families/ethereum/EthereumCustomFees.js

Fixes margin issues when a header is present at the top of the page (like when enabling experimental features). 
<details>
<summary>Screenshot(s) 📸 </summary>
<br/><br/>
*With "experimental features" header*
-----
*Without any header*
</details>
Bug Fix
[LL-6318]
- Enable at least one experimental feature 
- Start the send ethereum crypto flow
- Go to the summary step
- Click on `Customize fees`
- Check the margin
[LL-6318]: https://ledgerhq.atlassian.net/browse/LL-6318

LL-6318 - Ethereum Send flow step Summary: Add margin between GasPrice and GasLimit sections

---

src/locales/en/common.json

As counter values make no sense for our users, we're now displaying the label "preferred currency" which is more natural.
<details>
<summary>Mobile screenshots</summary>
</details>
Internationalization
[LL-6280]
Settings -> general
[LL-6281]: https://ledgerhq.atlassian.net/browse/LL-6281
[LL-6280]: https://ledgerhq.atlassian.net/browse/LL-6280

LL-6280 Update counter values translation

---

src/screens/NotificationCenter/Status.js

Adds some padding in the incidents status view when everything is ok.
<details>
<summary>Screenshot 📸 </summary>
</details>
Bug Fix
[LL-6002]
Navigation Center (top-right bell icon) -> Status Tab
*Reproducible only when the incidents count is 0.*
[LL-6002]: https://ledgerhq.atlassian.net/browse/LL-6002

LL-6002 Status, need top margin when Live is up and running

---

src/screens/NotificationCenter/NotificationsProvider.js
src/screens/Settings/Debug/GenerateAnnouncementMockData.js

Feature
[LL-6084]
Announces.
To test this feature, you will have to wait for the ledger-live-common bump. Current modification from ledger-live-common is [here](https://github.com/LedgerHQ/ledger-live-common/pull/1310). Once this PR is merged, the ledger-live-common package published and updated from this repository, you'll be able to test it.
[LL-6084]: https://ledgerhq.atlassian.net/browse/LL-6084

LL-6084 - Filter ANN by Live versions

---

src/components/WebPlatformPlayer/index.js

Fix error at the end of sign transaction flow when using ParaSwap dapp in "discover" tab (aka apps catalog)
<details>
<summary>🎥  </summary>
https://user-images.githubusercontent.com/87011321/127208970-c03a960b-2fbf-465a-9054-b08b04df4937.mov
</details>
🐞  Bug Fix
https://ledgerhq.atlassian.net/browse/LL-6527
Apps catalog and more precisely the sign transaction flow in the Apps catalog.
Test that it fixes the aforementioned issue in ParaSwap.
Validate that it does not change the behaviour for other dapps using a sign transaction flow (maybe Wyre but not sure)

[BUGFIX] remove duplicated dangerouslyGetParent call

---

src/screens/Swap/FormOrHistory/Form/Amount.js

With the merger of the Wyre pr I introduced a regression that set the default trade method back to fixed, I assume this was done during development for some reason and I completely missed it.
Bug fix
https://ledgerhq.atlassian.net/browse/LL-6597
Check that when selecting a currency pair the default trade method selected is float when available

LL-6597 Swap - Make floating rate default again

---

src/components/WebPlatformPlayer/InfoPanel.js
src/components/WebPlatformPlayer/index.js
src/locales/en/common.json

Add a "drawer" for platform apps when you're clicking on an info button at the top of the app.
<details>
<summary>iOS 📸 </summary>
&nbsp;
</details>
<details>
<summary>Android 📸 </summary>
&nbsp;
</details>
Feature
[LL-6362](https://ledgerhq.atlassian.net/browse/LL-6362)
Any platform app.
For test purposes, the icon and url are not mandatory.

LL-6369 - Add info panel for platform apps

---

src/locales/en/common.json
src/screens/Swap/FormOrHistory/Form/DisclaimerModal.js

Just the capital 'C'
UI Polish
https://ledgerhq.atlassian.net/browse/LL-6032
- Access the swap feature (make sure you are not pointing to v3 still like I was)
- Reach the summary step
- Continue. On this confirmation modal you will see the wording above, make sure the provider is capitalized, ie no "changelly" but rather "Changelly"

LL-6032 (Swap) Capitalize the provider name in the disclaimer modal

---

src/components/KeyboardView.js
src/screens/Settings/Experimental/ExperimentalHeader.js

Fixes keyboard covering up the bottom of the visible screen when the `Experimental features` header is displayed.
<details>
<summary>Iphone 8 📸 </summary>
</details>
<details>
<summary>Iphone 11 📸 </summary>
</details>
<details>
<summary>Android 📸 </summary>
---
</details>
Bug Fix
[LL-6317]
- Select any input triggering the keyboard on IOS.
- The bottom of the screen should not be hidden by the keyboard any more.
*The original issue was specifically about the "Amount" step of the "Send" flow, but my understanding is that it happens for any input.*
[LL-6317]: https://ledgerhq.atlassian.net/browse/LL-6317

LL-6317 Send flow step amount: Continue CTA shouldn't be hidden by keyboard

---

src/screens/OperationDetails/Content.js

Pressing on the Account on the OperationDetails view was opening a View with the same animation as a Drawer + it could lead to an infinite stacking of views when coming from the portfolio. 
<details>
<summary>iOS 📸 </summary>
https://user-images.githubusercontent.com/86959861/125322718-5cd6f180-e33e-11eb-95d2-5d07ca53c88a.mp4
</details>
<details>
<summary>Android 📸 </summary>
https://user-images.githubusercontent.com/86959861/125324955-b2140280-e340-11eb-937f-ee709c847f7c.mp4
</details>
Bug Fix
[LL-5174](https://ledgerhq.atlassian.net/browse/LL-5174)
Portfolio -> Transaction -> Click on Account ID
Portfolio -> Assets -> Long Press on Asset -> Transaction -> Click on Account ID
Accounts -> Account -> Transaction -> Click on Account ID

LL-5174 - Change navigation in OperationDetails to prevent navigation stack infinite loop

---

src/components/RootNavigator/SwapNavigator.js
src/experimental.js
src/screens/Swap2/index.js

- Created a blank swap v2 entry screen.
- Added an experimental flag to switch between regular and in-progress swap screens. (*only in `__DEV__` mode*)
https://user-images.githubusercontent.com/86958797/130048720-f6a6b098-9b27-4702-be45-dda61bbec3b8.mp4
Chore
https://ledgerhq.atlassian.net/browse/LL-6301
Swap V2 landing screen & Experimental flags

LL6301 - Swap v2 entry point

---

src/components/Button.js

Fix the way we allocate testID to an element:
- If `testID` exists on an element we use it
- If button is primary `testID="proceed"`
- Otherwise fallback to `event`
- To see the `testID`: Button should be visible on the screen and shouldn't be disabled 
Detox framework setup
UI test automation

Detox UI test framework: fix testID allocation

---

src/components/WebPlatformPlayer/index.js

Feature
[LL-6407]
Nothing should be affected, this fix allow ledger live mobile to use the dapp-browser v2, which is not used in production currently. Dapps should be still working as expected
[LL-6407]: https://ledgerhq.atlassian.net/browse/LL-6407

added optional param field in manifest

---

src/locales/en/common.json
src/screens/NotificationCenter/Snackbar/Snackbar.js
src/screens/NotificationCenter/Snackbar/SnackbarContainer.js

For the cases where we might have more than one notification, show a groupal one instead that opens the notification centre to avoid cluttering the screen with them
Feature
https://ledgerhq.atlassian.net/browse/LL-6789
- Access the debug menu, then the notification screen
- Trigger one notification and make sure it looks OK and is interactive 
- Trigger a second notification an make sure they are now grouped as a single one
https://user-images.githubusercontent.com/4631227/133086829-5dd94035-719d-4a35-954c-b81acc980924.mov

LL-6789 Group toast notifications into a single one

---

deep-links-test-page.html
src/index.js
src/navigation/useDeepLinking.js
src/screens/Platform/App.js
src/screens/Platform/index.js

Adding deeplinks to the platform catalog and dapps
<details>
<summary> iOS</summary>
https://user-images.githubusercontent.com/86959861/132313597-7c727b3e-70bc-4bd6-a792-1106149f4e27.mov
</details>
Feature
[LL-6884](https://ledgerhq.atlassian.net/browse/LL-6884)
Deep Links:
`ledgerlive://discover`
`ledgerlive://discover/paraswap` (or any other app id)
`ledgerlive://discover/paraswap?theme=dark` (or any other param that would make sense to pass to the dapp)

LL 6884 - Add discover deeplink

---

src/components/TabIcon.js
src/screens/Account/SubAccountsList.js

- [LL-6906](https://ledgerhq.atlassian.net/browse/LL-6906) Can't really be tested without changing the wording manually, to do this edit the `src/locales/fr/common.json` and edit `account.tokens.addTokens` to be something longer than just "Tokens", the button cta should grow like in the screenshot instead of being cut-off like on the Jira task.
- [LL-6907](https://ledgerhq.atlassian.net/browse/LL-6907) You simply need to switch between french and english in the settings and make sure that the bottom tab navigation labels are translated (there's the case for "Discover" which is not translated, so this doesn't apply), on develop there seems to be a cache where portfolio and accounts keep the old language when switching, this should not happen in this pr.
UI Polish + Bug Fix …

LL-6906 LL-6907 Allow for a bigger cta for add tokens Language cache bug

---

src/analytics/segment.js

All events emitted should have a property `language` set to the user's preferred language's corresponding key ("en", "fr", etc.)
Analytics
[LL-7871]
[LL-7871]: https://ledgerhq.atlassian.net/browse/LL-7871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-7871 Add language to analytics extra properties

---

src/components/FirmwareUpdateBanner.js

The firmware update banner was using the firmware's version instead of its name.
The PR changes it to use the name.
Bug Fix
[LL-7547]
Firmware update banner
[LL-7547]: https://ledgerhq.atlassian.net/browse/LL-7547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-7547 Use firmware's name instead of version on update banner

---

deep-links-test-page.html
docs/linking.md
src/index.js
src/navigation/useDeepLinking.js
src/screens/Manager/index.js

[LL-6736] - Integrate Manager in URI Scheme
`ledgerlive://manager` will point to the manager page 
It should also handle:
`ledgerlive://manager?installapp=appName` → With an anchor link that would redirect the user on click to the App’s position in the Catalog within the manager
https://user-images.githubusercontent.com/91890529/136361446-0ef7712d-b5fa-4ce1-931c-f04599d2192f.mov
Feature
[LL-6736]
1. Run `yarn run test-deep-links`
2. On the mobile device open one of the URL of the test-deep-links output.
3. In the mobile browser, open one of the two URIs "ledgerlive://manager"
4. **Expected result:** It should open Ledger Live and navigate to the Manager screen, and in case of the link that has a "installapp" search param it should prefill the search input with the value of the installapp …

LL-6736 Integrate Manager in URI Scheme

---

src/components/PasswordInput.js

> The branch number is wrong because I'm a moron.
The current behavior of the keyboard when entering the password screens is not ideal. The autofocus only takes effect on the first screen and will not show the keyboard on the confirmation one. I refactored the component (without judging the logic) into a functional component and will trigger the focus manually when mounting. This seems to solve the issue.
Bug Fix
https://ledgerhq.atlassian.net/browse/LL-4045
https://user-images.githubusercontent.com/4631227/135092916-9db9bd0d-f3c7-441b-86bc-9154f48f2738.mp4
- On an instance of LLM without a password setup a password
- Confirm that both screens (password + password confirmation) start with the keyboard open like in the video
- Confirm that we can still set up a password and remove it.
- …

LL-4045 Automatically display keyboard on password screens

---

src/screens/PairDevices/index.js

We've had this bug forever and it impacts 100% of our new pairings, impacting the UX of all our new users negatively. Just returning the full device instead of the deviceId allows the subsequent device action to actually connect when entering the manager and solves the issue. Just had to add a bunch of traces to see where it was breaking.
Bug fix 🐛 
[](https://ledgerhq.atlassian.net/browse/LL-6956)

LL-6956 Fix first pairing failure bug

---

package.json
src/components/RootNavigator/ImportAccountsNavigator.js
src/screens/ImportAccounts/DisplayResult.js

Due to a missed step in the [migration guide from v5.x to v6.x of `react-navigation` ](https://reactnavigation.org/docs/upgrading-from-5.x/#some-exports-are-now-moved-to-the-element-library) we were using an incorrect import path for the `HeaderBackButton` component, meaning the app would try to wrap undefined and crash whenever we relied on that import.
Bug fix
https://ledgerhq.atlassian.net/browse/LL-8135
- Import accounts via live qr
- Make sure the app doesn't crash on the result screen.

LL-8135 Fix crash after import

---

src/screens/Exchange/CoinifyWidget.js

Adds an opacity of `0.99` to the coinify webview in order to prevent a crash when navigating away.
Caused by compatibility issues between `react-native-webview` and `react-native-screens`.
See: 
- https://github.com/react-native-webview/react-native-webview/issues/1069
- https://github.com/software-mansion/react-native-screens/issues/105
Bug Fix
[LL-8167]
portfolio -> click buy
[LL-8167]: https://ledgerhq.atlassian.net/browse/LL-8167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-8167 - Fix webview crash when navigating away

---

src/components/AnimatedHeader.js
src/screens/Portfolio/index.js

Use `SafeAreaView` from `react-native-safe-area-context` to prevent escaping from the safe area.
React navigation recommends it for various reasons: https://reactnavigation.org/docs/handling-safe-area/
Bug Fix
[LL-8162]
- Portfolio screen empty states
- Portfolio screen when Carousel is displayed
- Platform -> apps catalog screen
[LL-8162]: https://ledgerhq.atlassian.net/browse/LL-8162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-8162 - Fix safe area issues

---

src/components/FabActions.js

The issue arises when separator components are in the first 2 elements of the actions array they are converted into empty buttons.
Bug Fix
[LL-8170]
- Read only mode (Onboarding without paring a device, import data from LLD)
- Ethereum Account screen
[LL-8170]: https://ledgerhq.atlassian.net/browse/LL-8170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-8170 - exclude empty buttons generated by separator components

---

src/components/LText/index.tsx

Infer Ltext font weight to ui's text - mark ltext as deprecated

LL-8036 - text infer deprecated

---

package.json
yarn.lock

A recent regression (bigint error when signing Bitcoin transactions with latest app) was fixed in @ledgerhq/live-common@21.16.2 (via ledgerjs hw-app-btc fix)
This PR upgrade live-common from 21.15.0 to 21.16.3 because it's consider the least impacting and most 1-1 with LLD current validated version. **The test impact should only be on the restoration of Bitcoin support**, because the workload was just on Bitcoin JS. (There are also regular ERC20 update in that work load).
- LLD is currently working with 21.16.0. So the 21.15.0 -> 21.16.0 changes shouldn't have surprise. It was only impacting the BTC JS implementation.
- the extra changes between 21.16.0 and 21.16.3 are mostly related to BTC JS as well. (the precise list is in https://github.com/LedgerHQ/ledger-live-common/releases but …

Update to live-common 21.16.3 to fix LL-8154

---

src/families/polkadot/TransactionConfirmFields.js

- (Polkadot): fix scrolling issue in device confirm fields
Bug Fix
[LL-8271]
Sending a tx on polkadot should now show all fields correctly with some scroll
[LL-8271]: https://ledgerhq.atlassian.net/browse/LL-8271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-8271 (Polkadot): fix scrolling issue in device confirm fields

---

src/StyleProvider.tsx

Old color palette was erasing new palette, reversed this. Also new color palette doesn't use only light theme anymore.
This fix the bug related to null backgroundColor prop crash.

Rebranding - Fix color palette

---

src/components/NavigationHeader.tsx
src/components/NavigationModalContainer.tsx
src/components/NavigationOverlay.tsx
src/components/RootNavigator/OnboardingNavigator.tsx
src/screens/Onboarding/steps/language.tsx
src/screens/Onboarding/steps/welcome.tsx

- improves navigation experience (pressing the previous button from the terms now goes back to the first welcome screen - not the modal)
- improves transitions - only the content is transitioned (not the header) and uses native animation style
- overall improvements to the modal container & header components
https://user-images.githubusercontent.com/86958797/144416158-3edc172d-3bcf-48d9-9822-45e567d1cb47.mp4
UI
[LL-7746]
[LL-7746]: https://ledgerhq.atlassian.net/browse/LL-7746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LL-7746 - Rebrand - Improve onboarding modals animations

---

package.json
yarn.lock

Bug fix
https://ledgerhq.atlassian.net/browse/LL-8926
I was able to fix this issues by taking an old version of the util lib.
The part of the problem was about BigInt into a Math.pow by using the `**` operator in polkadot lib.
It's seems to be find for this version but I don't know if it will work for later version (spoiler 7.5.1 just released yesterday, and LLD doesn't work anymore with this version 😠 )
https://github.com/polkadot-js/common/issues/1262#issuecomment-983995745
Polkadot, probably would be nice to retest the flow, but add accounts was mainly impacted

LL-8926: Fix polkadot bigInt issue

---

src/screens/PairDevices/Scanning.js

When pairing a BLE device on LLM we were relying solely on the device name and ignoring the fact that they might have renamed it already. We were only updating this app state level name when renaming the device so if we wanted to pair a 
forgotten device again, or pair a renamed device it would show (and keep) the old name and not the new one. 
Pretty low prio edge case, but quick win.
Bug fix
https://ledgerhq.atlassian.net/browse/LL-6987
- Pair a device, ie "Nano E123"
- Rename this device to "newname"
- Forget the device
- Scan for the device
- It is expected that the device shows up as "newname" and not "Nano E123"

LL-6987 Use localname for ble devices when available

---

package.json
yarn.lock

https://github.com/LedgerHQ/ledger-live-common/releases/tag/v21.33.0
---
- LL-9216 be less strict on breaking on non user accounts
- LL-9196 Update vtc explorer url
- LL-9198 crypto-assets list update
- LIVE-1123: low amount user shouldn't be able to set everything he want
- LIVE-825 - Update market API to have an AND logic on filters instead of OR logic 
- LIVE-1186 Update Polkadot Nano app min version to v10.9160.1 
- LIVE-1338 Remove Algorand JS impl from experimental mode
- LIVE-1337 Add check for recipient not equal to sender on crypto.org 
- LIVE-886 (Market): add sparkline variation + fix issue in countervalues 
---

live-common 21.33.0

---

src/screens/Manager/Modals/InstalledAppsModal.tsx

Fix the "my apps" modal in the manager page, **close button was hidden behind StatusBar**.
Fixed by adding a padding from `useSafeAreaInsets`.
Also did it in the bottom as it might affect screens on Android for instance when there is a transparent status bar.
Bug fix
v3 pre-release pixel polish

Fix InstalledAppsModal close button hidden behind status bar

---

src/components/DeviceAction/rendering.tsx

In buy flow (an possibly in other flows), the user has to check that the address displayed on device matches the one displayed in-app. The issue is that in the app it's written with uppercase.
With this fix we remove the "uppercase" text transformation that was applied in the component displaying the address, so the address will be displayed with its original casing.
Bug fix
[LIVE-2214]
[LIVE-2214]: https://ledgerhq.atlassian.net/browse/LIVE-2214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIVE-2214 - Disable uppercase when displaying an address in DeviceAction

---

package.json
yarn.lock

No breaking changes in that upgrade.
Adding external link icon next to notification link
Dependency upgrade
[LIVE-1981]
Notifications screen
[LIVE-1981]: https://ledgerhq.atlassian.net/browse/LIVE-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Upgrade @ledgerhq/native-ui to 0.7.16, addressing LIVE-1981
